package com.centris.campus.util;

public class LeaveBankSqlUtil {

	public static final String ADD_LEAVE_TYPES = "INSERT INTO `campus_leave_types` (`leavecode`,`accid`,`locid`,`leavename`,`noofleaves`,`carryforward`,`createdby`,createddate,`isGenderSpec`,`isprobationary`,`min_lea_per_month`,`max_leav_per_month`,`max_consecu_lea_perm`,`week_off_inclusion`,`leave_cycle`) VALUES (?,?,?,?,?,?,?,NOW(),?,?,?,?,?,?,?)";
	public static final String UPDATE_LEAVE_TYPES_DETAILS = "UPDATE `campus_leave_types` SET `leavecode` = ?, `leavename` = ?, `noofleaves` = ?,`carryforward` = ?, `modifiedby` = ?,`leave_cycle`=?,`isGenderSpec` =?,`isprobationary`=?,`min_lea_per_month`=?,`max_leav_per_month`=?,`max_consecu_lea_perm`=?,`week_off_inclusion`=? WHERE `leaveid` = ?";
	public static final String DELETE_LEAVE_TYPES_DETAILS = "DELETE FROM campus_leave_types WHERE `leaveid` = ?";
	public static final String CHECK_LEAVE_CODE = "SELECT COUNT(*) FROM `campus_leave_types` WHERE `leavecode` = ? AND `accid` = ? AND `locid` = ?";
	public static final String CHECK_LEAVE_NAME = "SELECT COUNT(*) FROM `campus_leave_types` WHERE `leavename` = ? AND `accid` = ? AND `locid` = ?";
	public static final String GET_LEAVE_MAP_STATUS = "SELECT DISTINCT `acadamic_id`,`acadamic_year`,`Location_Id`,`Location_Name`,CASE WHEN (SELECT COUNT(*) FROM staff_leaves_details WHERE sl.accy_id = ? AND sl.`loc_id` LIKE ?) = 0 THEN 'Not Set' ELSE 'Set' END mstatus FROM (`campus_acadamicyear` a,`campus_location` l) LEFT JOIN `staff_leaves_details` sl ON sl.accy_id = acadamic_id AND sl.`loc_id` = Location_Id WHERE acadamic_id = ? AND Location_Id LIKE ? AND a.`isActive` = 'Y' AND l.`isActive` = 'Y'  ORDER BY `startDate`,`Location_Name`";
	public static final String GET_STAFF_LEAVE_MAP_STATUS = "SELECT staff_leave_id,registerId,`TeacherID`,CONCAT(`FirstName`,' ',`LastName`) AS teacher,`registerId`,`acadamic_id`,`acadamic_year`,`Location_Id`,`Location_Name`,CASE WHEN ( (SELECT COUNT(*) FROM `staff_leaves_details` WHERE `accy_id` = ? AND `loc_id` = ? AND `staff_id` = TeacherID) = 0) THEN 'Not Set' ELSE  'Set' END mstatus FROM (`campus_acadamicyear` a ,`campus_teachers` t  JOIN `campus_location` l ON l.`Location_Id` = t.Loc_ID AND l.`isActive` = 'Y') LEFT JOIN `staff_leaves_details` ct ON ct.`staff_id` = t.`TeacherID` AND ct.`accy_id` = ? WHERE t.`Loc_ID` = ? AND t.isActive = 'Y' AND `acadamic_id` = ? AND a.`isActive` = 'Y' AND `dateofJoining` <= a.`endDate`  ORDER BY `startDate`,`Location_Name`,teacher";
	public static final String INSERT_STAFF_LEAVE_DETAILS = "INSERT INTO `staff_leaves_details` (`accy_id`,`loc_id`,`staff_id`,`created_date`,`created_by`) VALUES(?,?,?,now(),?)";
	public static final String INSERT_STAFF_LEAVE_MAP_DETAILS = "INSERT INTO `staff_leaves_mapping` (`staff_leave_id`,`leave_id`,`leaves_applicable`) VALUES(?,?,?)";
	public static final String GET_STAFF_MAPPED_LEAVES = "SELECT `leavecode`,`leaveid`,`leavename`,`noofleaves`,`leaves_applicable` FROM `staff_leaves_mapping` lm JOIN `staff_leaves_details` ld ON lm.`staff_leave_id` = ld.`staff_leave_id` JOIN `campus_leave_types` lt ON lt.`leaveid` = lm.`leave_id` WHERE ld.`staff_leave_id` = ? AND `accy_id` = ? AND `loc_id` = ? AND staff_id = ?";
	public static final String UPDATE_STAFF_LEAVES = "UPDATE `staff_leaves_mapping` SET `leaves_applicable` =? WHERE `staff_leave_id` = ? AND `leave_id` = ?";
	public static final String GET_UNMAPPED_STAFF_LEAVES = "SELECT `leaveid`,`leavecode`,`leavename`,`noofleaves` FROM `campus_leave_types` WHERE `leaveid` NOT IN (SELECT `leave_id` FROM `staff_leaves_mapping` sm JOIN `staff_leaves_details` sl ON  sl.`staff_leave_id` = sm.`staff_leave_id` AND sl.`accy_id` = ? AND sl.`loc_id` = ? AND sl.`staff_id` = ?) AND `accid` = ? AND `locid` = ?  ORDER BY `leavename`";
	public static final String CHECK_LEAVE_MAP_STATUS = "SELECT COUNT(*) FROM `staff_leaves_details` WHERE `accy_id` = ? AND `loc_id` = ? AND `staff_leave_id` = ? AND `staff_id` = ?";
	public static final String GET_STAFF_LEAVE_BANK_DETAILS = "SELECT `leaves_applicable`,`total_leave_consumed`,`bal_leaves`,`noofleaves`,`leave_id` FROM `staff_leaves_details` sl JOIN `staff_leaves_mapping` sm ON sl.`staff_leave_id` = sm.`staff_leave_id` JOIN `campus_leave_types` l ON l.`leaveid` = sm.`leave_id` WHERE sl.`accy_id` = ? AND sl.`loc_id` = ? AND sl.`staff_id` = ? AND sm.`leave_id` =  ?";
	public static final String STAFF_MAP_LEAVE_DETAILS = "SELECT CONCAT(`FirstName`,' ',`LastName`)AS teacher,`registerId`,`leaves_applicable`,`total_leave_consumed`,`bal_leaves`,lp.`noofleaves`FROM `campus_teachers` t JOIN `staff_leaves_details` sl ON t.`TeacherID` = sl.`staff_id`JOIN `staff_leaves_mapping` sm ON sm.`staff_leave_id` = sl.`staff_leave_id` JOIN `campus_leave_types` lp ON lp.`leaveid` = sm.`leave_id` WHERE sl.`accy_id` = ? AND sl.`loc_id` like ? AND sm.`leave_id`  = ?";
	public static final String STAFF_DETAILS = "SELECT DISTINCT CONCAT(`FirstName`,' ',`LastName`)AS teacher,`registerId`,t.`Loc_ID`AS tloc,TeacherID FROM `campus_acadamicyear` a,`campus_teachers` t JOIN `campus_location` l ON t.Loc_ID = l.`Location_Id` AND l.`isActive` = 'Y' JOIN `staff_leaves_details` sl ON sl.`staff_id` = t.`TeacherID` AND sl.`loc_id` = t.`Loc_ID` AND t.`isActive` = 'Y' AND sl.`accy_id`= ? WHERE t.`Loc_ID` LIKE ? AND a.`acadamic_id` = ? AND `dateofJoining` <= `endDate` ORDER BY teacher";
	public static final String GET_STAFF_LEAVES = "SELECT `leaveid`,CONCAT(`leavecode`,' - ',`leavename`)AS lname FROM `campus_teachers` t JOIN `staff_leaves_details` sl ON t.`TeacherID` = sl.staff_id AND t.`isActive` = 'Y' AND t.`Loc_ID` = sl.`loc_id` "+
												  "JOIN `staff_leaves_mapping` sm ON sl.`staff_leave_id` = sm.`staff_leave_id` JOIN `campus_leave_types` l "+ 
												  "ON l.`leaveid` = sm.`leave_id`  WHERE sl.`accy_id` = ? AND `staff_id` = ? and isGenderSpec IN('A',?)";
	public static final String GET_APPROVER_DETAILS = "SELECT `TeacherID`,CONCAT(`FirstName`,' ',`LastName`) AS teacher FROM campus_teachers t JOIN `campus_leave_aprover` la ON la.`approver_id` = t.TeacherID WHERE la.`leave_id` = ?";
	public static final String GET_BAL_DETAILS = "SELECT l.leaveid,leavecode,`leaves_applicable`,`total_leave_consumed`,`bal_leaves`,`leavename`,`acadamic_year`,`Location_Name` "+
												  "FROM `campus_teachers` t JOIN `staff_leaves_details` sl ON t.`TeacherID` = sl.staff_id AND t.`isActive` = 'Y' AND t.`Loc_ID` = sl.`loc_id` JOIN `staff_leaves_mapping` sm ON sm.`staff_leave_id` = sl.`staff_leave_id` JOIN "+ 
												  "`campus_leave_types` l ON l.`leaveid` = sm.`leave_id` and isGenderSpec IN('A',?) JOIN `campus_acadamicyear` a ON a.`acadamic_id` = sl.accy_id "+ 
												  "JOIN `campus_location` loc ON loc.`Location_Id` = sl.loc_id "
												  + "WHERE `accy_id` = ? AND `staff_id` = ?";
	public static final String GET_LEAVE_POLICY = "SELECT locid,leavecode,week_off_inclusion,accid,`acuumulation`,`carryforward`,`leave_cycle`,`leavename`,`noofleaves`,CASE WHEN `custom_stdate` IS NULL THEN '-' ELSE custom_stdate END custom_stdate,CASE WHEN `custom_enddate` IS NULL THEN '-' ELSE custom_enddate END custom_enddate,`isprobationary`,`min_lea_per_month`,`max_leav_per_month`,`max_consecu_lea_perm`,isGenderSpec FROM `campus_leave_types` WHERE `leaveid` = ?"; 
	public static final String GET_STAFF_LEAVE_MAP_DETAILS = "SELECT `leaves_applicable`,`total_leave_consumed`,`bal_leaves`,`noofleaves`,`leave_id`,CONCAT(`FirstName`,' ',`LastName`)AS teacher,`registerId`,t.`Loc_ID`AS tloc,TeacherID \r\n" + 
															 "FROM `campus_teachers` t JOIN `staff_leaves_details` sl ON sl.`staff_id` = t.`TeacherID` AND sl.`loc_id` = t.`Loc_ID` AND t.`isActive` = 'Y' \r\n" + 
															 "JOIN `staff_leaves_mapping` sm ON sl.`staff_leave_id` = sm.`staff_leave_id` JOIN `campus_leave_types` l ON l.`leaveid` = sm.`leave_id` \r\n" + 
															  "WHERE sl.`accy_id` = ? AND sl.`loc_id` = ? AND sm.`leave_id` =  ?";
	public static final String GET_LEAVE_APPROVER = "SELECT CONCAT(`FirstName`,' ',`LastName`),re.`TeacherID` FROM `campus_teachers` re JOIN `campus_role` r ON `role` = r.`RoleCode` AND r.`IsDefault` = 'Y' AND  r.`isActive` = 'Y' WHERE re.`Loc_ID` = ? AND re.isActive = 'Y'";		
}
