package com.centris.campus.util;

public class SmsUtilsConstants {
	
	public static final String GET_CLASS_LIST = "select classdetail_id_int,classdetails_name_var from campus_classdetail order by classdetails_name_var";
	
	public static final String GET_SECTION_LIST = "select classsection_id_int,classsection_name_var from campus_classsection where classdetail_id_int=?";

	public static final String GET_SUBJECT_LIST = "SELECT DISTINCT `subjectID`,`subjectName`FROM `campus_subject` cs JOIN `campus_classdetail` ccd ON ccd.`classdetail_id_int`=cs.`classid` AND cs.`isActive`='Y' AND cs.`classid`=? AND cs.locationId=? ORDER BY subjectName";
	
	public static final String INSERT_HOMEWORK = "insert into campus_homework (homeworkid,dateid,classid,sectionid,subjectid,description,createdate,createuser,LocId,studentId,accyId) values(?,?,?,?,?,?,?,?,?,?,?)";
	
	public static final String GET_HOMEWORK_LIST ="SELECT DISTINCT hm.homeworkid,hm.dateid,cls.classdetails_name_var,sec.classsection_name_var,sub.subjectName,hm.description ,cl.`Location_Name`,sa.`sms_status`,hm.createdate FROM campus_homework hm JOIN campus_classdetail cls ON cls.classdetail_id_int=hm.classid AND cls.`locationId`=hm.`LocId` AND cls.`isActive`='Y' JOIN campus_classsection sec ON sec.classsection_id_int=hm.sectionid  AND sec.`locationId`=hm.`LocId` AND sec.`isActive`='Y' JOIN campus_subject sub ON sub.subjectID=hm.subjectid AND sub.`isActive`='Y' JOIN `campus_location` cl ON cl.`Location_Id`=hm.`LocId` AND cl.`isActive`='Y' JOIN `sms_audit` sa ON sa.`ServiceCode`= hm.`homeworkid` WHERE hm.`LocId`=?";
	
	public static final String SEARCH_HOMEWORK_LIST = "SELECT DISTINCT hm.homeworkid,hm.dateid,cls.classdetails_name_var,sec.classsection_name_var,sub.subjectName,hm.description ,cl.`Location_Name` FROM campus_homework hm JOIN campus_classdetail cls ON cls.classdetail_id_int=hm.classid JOIN campus_classsection sec ON sec.classsection_id_int=hm.sectionid JOIN campus_subject sub ON sub.subjectID=hm.subjectid JOIN `campus_location` cl ON cl.`Location_Id`=hm.`LocId` WHERE  hm.`LocId` like ? AND hm.`classid` like ? AND hm.`sectionid` like ? and hm.accyId=? and hm.dateid between ? and ? ";

	public static final String DELETE_HOMEWORK = "delete from campus_homework where homeworkid=?";

	public static final String GET_MEETING_LIST ="SELECT me.meetingid,me.meetingdate,me.title,me.starttime,me.endtime,me.studentname,sm.`sms_status`,me.`locId`,me.`accyear`,CASE WHEN me.subjectname='general' THEN me.subjectname ELSE(SELECT subjectName FROM campus_subject WHERE subjectID=me.subjectname) END subjectname,me.venuedetails,me.createdate FROM sms_meeting me JOIN  `sms_audit` sm ON sm.`ServiceCode`=me.`meetingid` JOIN campus_classdetail cls ON cls.classdetail_id_int=me.`classid`AND cls.`locationId`=me.`locId`AND cls.`isActive`='Y' JOIN campus_classsection sec ON sec.classsection_id_int=me.`sectionid`  AND sec.`locationId`=me.`locId`AND sec.`isActive`='Y' JOIN `campus_location` cl ON cl.`Location_Id`=me.`LocId` AND cl.`isActive`='Y' WHERE me.`locId`=? ORDER BY me.meetingdate DESC";
	
	public static final String GET_SUBJECT_DETAILS = "select subjectID,subjectName from campus_subject where classid=?";
	
	public static final String GET_STUDENT_DETAILS ="SELECT DISTINCT cs.student_id_int,CONCAT(cs.student_fname_var,' ',cs.student_lname_var)AS studentname FROM campus_student cs JOIN campus_student_classdetails csc ON cs.student_id_int=csc.student_id_int JOIN campus_classdetail ccd ON ccd.classdetail_id_int=csc.classdetail_id_int JOIN campus_location cl ON cl.Location_Id=csc.locationId JOIN campus_acadamicyear cay ON cay.acadamic_id=csc.fms_acadamicyear_id_int WHERE cs.locationId=? AND csc.fms_acadamicyear_id_int=? AND csc.classdetail_id_int=? AND `student_status_var`='active'";

	public static final String SAVE_MEETING ="INSERT INTO sms_meeting (meetingid,meetingdate,title,locId,classid,sectionid,starttime,endtime,subjectname,studentname,description,createuser,createdate,accyear) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static final String DELETE_MEETING = "delete from sms_meeting where meetingid=?";
	
	public static final String SEARCH_MEETING_LIST = "select meetingid,meetingdate,title,starttime,endtime,venuedetails from  sms_meeting where meetingid like ? or meetingdate like ? or title like ? or starttime like ? or endtime like ? or venuedetails like ?";

	public static final String SAVE_LATE = "INSERT INTO latecomers_sms (Late_Comers_Code,LocId,AccyearId,Student_Code,Class_Code,Section_Code,DATE,Description,CreatedUser) VALUES(?,?,?,?,?,?,?,?,?)";

	public static final String GET_STUDENT_DETAILS_VAL = "SELECT se.classsection_id_int,re.relationship,(CASE WHEN re.relationship='father' THEN par.mobileno WHEN re.relationship='mother' THEN par.student_mothermobileno_var WHEN re.relationship='guardian' THEN par.student_gardian_mobileno ELSE '1' END) AS student_contact_mobileno, cl.classdetail_id_int,cl.classdetails_name_var,stu.student_id_int,stu.student_fname_var FROM campus_student stu JOIN campus_student_classdetails cscd ON cscd.student_id_int = stu.student_id_int JOIN campus_classdetail cl ON cl.classdetail_id_int = cscd.classdetail_id_int AND  cl.`locationId`=cscd.`locationId`JOIN campus_classsection se ON se.classsection_id_int = cscd.classsection_id_int AND se.`locationId`=cscd.`locationId` JOIN campus_parentchildrelation re ON re.stu_addmissionNo = stu.student_id_int JOIN campus_parents par ON par.ParentID = re.parentid WHERE stu.student_id_int =?";

	public static final String GET_LATECOMERS_LIST ="SELECT DISTINCT lcs.Late_Comers_Code,lcs.Date,cl.Location_Name,CONCAT(cs.student_fname_var,' ',cs.student_lname_var)AS studentname,ccd.classdetails_name_var,ccs.classsection_name_var,lcs.Description,sa.`sms_status`,lcs.Created_Time FROM latecomers_sms lcs JOIN campus_location cl ON cl.Location_Id=lcs.LocId AND cl.`isActive`='Y' JOIN campus_classdetail ccd ON ccd.classdetail_id_int=lcs.Class_Code AND ccd.`locationId`=lcs.`LocId`AND ccd.`isActive`='Y' JOIN campus_classsection ccs ON ccs.classsection_id_int=lcs.Section_Code  AND ccs.`locationId`=lcs.`LocId` AND ccs.`isActive`='Y' JOIN campus_student_classdetails csc ON (csc.classdetail_id_int=lcs.Class_Code AND csc.classsection_id_int= lcs.Section_Code) JOIN campus_student cs ON cs.student_id_int=lcs.Student_Code JOIN campus_acadamicyear cay ON cay.acadamic_id=lcs.AccyearId  AND cay.`isActive`='Y' JOIN `sms_audit` sa ON sa.`ServiceCode`=lcs.`Late_Comers_Code` WHERE lcs.`LocId`=?";
	
	public static final String STORE_UNIFORM_SMS_DETAILS = "insert into sms_uniform_details(UNIFORM_CODE,UNIFORM_DATE,UNIFORM_CONTENT,IsSection,IsStudent,SMS_STATUS,CREATE_TIME,CREATED_BY) values(?,?,?,?,?,?,?,?)";
	
	public static final String STORE_UNIFORM_SECTION_DETAILS = "insert into sms_uniform_section(UNIFORM_CODE,SECTION_CODE,CREATED_TIME,CREATED_BY) values(?,?,?,?)";

	public static final String STORE_UNIFORM_STUDENT_DETAILS = "insert into sms_uniform_student(UNIFORM_CODE,STUDENT_ADM_NO,CREATED_TIME,CREATED_BY) values(?,?,?,?)";

	public static final String GET_ABSENT_SMS = "select  stu.student_admissionno_var,det.CREATED_BY,stu.student_id_int,stu.classsection_id_int,det.ABSENT_DATE smsDate,det.ABSENT_CONTENT as smsContent,re.relationship,(case when re.relationship='father' then par.mobileno when re.relationship='mother' then par.student_mothermobileno_var when re.relationship='guardian' then par.student_gardian_mobileno else '1' end)as student_contact_mobileno,par.ParentID from campus_parents par join campus_parentchildrelation re on re.parentid = par.ParentID join campus_student stu on stu.student_id_int = re.stu_addmissionNo join sms_absent_student hol on hol.STUDENT_ADM_NO = stu.student_id_int join sms_absent_details det on det.ABSENT_CODE = hol.ABSENT_CODE where hol.ABSENT_CODE= ? and det.ABSENT_DATE=? ";
	
	public static final String GET_UNIFORM_LIST ="SELECT distinct us.Uniform_Code,cl.Location_Name,CONCAT(cs.student_fname_var,' ',cs.student_lname_var)AS studentname,ccd.classdetails_name_var,ccs.classsection_name_var,us.Description,us.Date FROM uniform_sms us JOIN campus_location cl ON us.LocId=cl.Location_Id JOIN campus_classdetail ccd ON ccd.classdetail_id_int=us.Class_Code JOIN campus_classsection ccs ON ccs.classsection_id_int=us.Section_Code JOIN campus_acadamicyear cay ON cay.acadamic_id=us.AccyearId JOIN campus_student_classdetails csc ON (csc.classdetail_id_int=us.Class_Code AND csc.classsection_id_int= us.Section_Code)JOIN campus_student cs ON cs.student_id_int=us.Student_Code";
	
	public static final String GET_SECTION_DETAILS = "select us.UNIFORM_CODE,us.SECTION_CODE,sec.classsection_name_var from sms_uniform_section us join campus_classsection sec on sec.classsection_id_int=us.SECTION_CODE where us.UNIFORM_CODE=?";
	
	public static final String GET_STUDENT_UNIFORM_DETAILS = "";

	public static final String SAVE_UNIFORM ="INSERT INTO uniform_sms (Uniform_Code,LocId,AccyearId,Student_Code,Class_Code,Section_Code,DATE,CreatedUser,Description) VALUES(?,?,?,?,?,?,?,?,?)";
	
	public static final String SAVE_BIRTHDAY = "insert into birthday_sms(bdaycode,bdaydate,classcode,sectioncode,studentcode,smscontent,createuser,createTime) values(?,?,?,?,?,?,?,now())";
	
	public static final String GET_BDAY_LIST = "select bd.bdaycode,bd.bdaydate,bd.classcode,bd.sectioncode,bd.studentcode,bd.smscontent,cls.classdetails_name_var,sec.classsection_name_var,stu.student_fname_var from birthday_sms bd join  campus_classdetail cls on cls.classdetail_id_int=bd.classcode join campus_classsection sec on sec.classsection_id_int=bd.sectioncode join campus_student stu on stu.student_id_int=bd.studentcode order by bd.bdaycode";

	public static final String INSERT_FEE_DETAILS = "insert into sms_fee_details (FEE_CODE,FEE_DATE,STU_ID,FEE_CONTENT,TOTAL_AMT,PAID_AMT,BALANCE_AMT,CREATED_BY,CREATE_TIME) values(?,?,?,?,?,?,?,?,?)";

	public static final String SEND_FEE_DETAILS = "select stu.student_admissionno_var,fee.FEE_DATE as smsDate,fee.FEE_CONTENT as smsContent,fee.CREATE_TIME,fee.CREATED_BY,(case when re.relationship='father' then par.mobileno when re.relationship='mother' then par.student_mothermobileno_var when re.relationship='guardian' then par.student_gardian_mobileno else '1' end)as student_contact_mobileno,par.ParentID from sms_fee_details fee join campus_parentchildrelation re on re.stu_addmissionNo =fee.STU_ID join campus_parents par on par.ParentID=re.parentid join campus_student stu on stu.student_id_int = fee.STU_ID where FEE_CODE=? and FEE_DATE=?";

	public static final String GET_FEE_DETAILS = "Select distinct f.*,concat(stu.student_fname_var,' ',student_lname_var) as name,stu.student_admissionno_var from campus_payment_collection f,campus_student stu where stu.student_admissionno_var=f.student_admission and feesettings_id=?";

	public static final String CHECK_BDAY_DATE = "select count(*) from campus_student where  student_dob_var like ?";

	public static final String GET_SMS_DETAILS_FOR_BDAY = "select concat(stu.student_fname_var,' ',student_lname_var) as name,stu.student_id_int,stu.classdetail_id_int,stu.classsection_id_int,(case when re.relationship='father' then par.mobileno when re.relationship='mother' then par.student_mothermobileno_var when re.relationship='guardian' then par.student_gardian_mobileno else '1' end)as student_contact_mobileno from campus_student stu join campus_parentchildrelation re on re.stu_addmissionNo =stu.student_id_int join campus_parents par on par.ParentID = re.parentid where stu.student_dob_var like ?";
	
	public static final String GET_SUBJECT_DETAILS_VAL = "select stu.student_id_int,re.relationship,(case when re.relationship='father' then par.mobileno when re.relationship='mother' then par.student_mothermobileno_var  when re.relationship='guardian' then par.student_gardian_mobileno else '1' end) as student_contact_mobileno,stu.student_fname_var,cl.classdetails_name_var,sub.subjectID,sub.subjectName from campus_subject sub join campus_classdetail cl on cl.classdetail_id_int = sub.classid join campus_student stu on stu.classdetail_id_int = cl.classdetail_id_int join campus_parentchildrelation re on re.stu_addmissionNo = stu.student_id_int join campus_parents par on par.ParentID = re.parentid where sub.subjectID = ?";

	public static final String GET_SUB_DETAILS = "SELECT stu.student_id_int,re.relationship,(CASE WHEN re.relationship='father' THEN par.mobileno WHEN re.relationship='mother' THEN par.student_mothermobileno_var  WHEN re.relationship='guardian' THEN par.student_gardian_mobileno ELSE '1' END) AS student_contact_mobileno,stu.student_fname_var,cl.classdetails_name_var,sub.subjectID,sub.subjectName FROM campus_subject sub JOIN campus_classdetail cl ON cl.classdetail_id_int = sub.classid JOIN campus_student_classdetails csc ON csc.classdetail_id_int=cl.classdetail_id_int JOIN campus_student stu ON stu.`student_id_int` = csc.student_id_int JOIN campus_parentchildrelation re ON re.stu_addmissionNo = stu.student_id_int JOIN campus_parents par ON par.ParentID = re.parentid WHERE sub.subjectID=?";

	public static final String SAVE_OTHERS = "insert into sms_othersms (other_sms_id,studentid,classid,sectionid,entry_date,created_by) values(?,?,?,?,?,?)";

	public static final String GET_PARENT_NO ="SELECT (CASE WHEN pc.relationship='father' THEN par.mobileno WHEN pc.relationship='mother' THEN par.student_mothermobileno_var WHEN pc.relationship='guardian' THEN par.student_gardian_mobileno ELSE '1' END)AS student_contact_mobileno FROM campus_parentchildrelation pc JOIN campus_parents par ON  par.ParentID = pc.parentid JOIN campus_student cs ON cs.student_id_int=pc.stu_addmissionNo WHERE cs.student_id_int=?";

	public static final String DELETE_HOME_WORK_DETAILS ="DELETE FROM campus_homework WHERE subjectid=?";

	public static final String GET_STUDENT_DETAILS_BY_SECTION ="SELECT cs.student_id_int,CONCAT(cs.student_fname_var,' ',cs.student_lname_var)AS studentname FROM campus_student cs JOIN campus_student_classdetails csc ON cs.student_id_int=csc.student_id_int JOIN campus_classsection ccs ON ccs.classsection_id_int=csc.classsection_id_int AND ccs.`locationId`= csc.`locationId` JOIN campus_classdetail ccd ON ccd.classdetail_id_int=csc.classdetail_id_int AND ccd.`locationId`= csc.`locationId` JOIN campus_location cl ON cl.Location_Id=csc.locationId JOIN campus_acadamicyear cay ON cay.acadamic_id=csc.fms_acadamicyear_id_int WHERE cs.locationId=? AND csc.fms_acadamicyear_id_int=? AND csc.classdetail_id_int=? AND csc.classsection_id_int=? AND `student_status_var`='active'";

	public static final String GET_STUDENT_SECTION_BY_STUID ="SELECT csc.classsection_id_int,(CASE WHEN pc.relationship='father' THEN par.mobileno WHEN pc.relationship='mother' THEN par.student_mothermobileno_var WHEN pc.relationship='guardian' THEN par.student_gardian_mobileno ELSE '1' END)AS student_contact_mobileno FROM campus_parentchildrelation pc JOIN campus_parents par ON  par.ParentID = pc.parentid JOIN campus_student cs ON cs.student_id_int=pc.stu_addmissionNo JOIN campus_student_classdetails csc ON cs.student_id_int=csc.student_id_int JOIN campus_classdetail ccl ON ccl.classdetail_id_int=csc.classdetail_id_int AND ccl.`locationId`=csc.`locationId`JOIN campus_location cloc ON cloc.Location_Id=csc.locationId JOIN campus_acadamicyear cay ON cay.acadamic_id=csc.fms_acadamicyear_id_int JOIN campus_classsection ccls ON ccls.classsection_id_int=csc.classsection_id_int AND ccls.`locationId`=csc.`locationId` WHERE cs.student_id_int=? AND csc.fms_acadamicyear_id_int=? AND csc.locationId=?";

	public static final String GET_PHNO_FOR_BDAY_STU = "SELECT DISTINCT CONCAT(stu.student_fname_var,' ',stu.student_lname_var)AS studentName,stu.student_dob_var,re.relationship,(CASE WHEN re.relationship='father' THEN par.mobileno WHEN re.relationship='mother' THEN par.student_mothermobileno_var WHEN re.relationship='guardian' THEN par.student_gardian_mobileno ELSE '1' END) AS student_contact_mobileno,cl.classdetail_id_int,cl.classdetails_name_var,se.classsection_id_int,se.classsection_name_var,stu.student_id_int,stu.student_fname_var,stu.student_admissionno_var,stu.locationId,loc.Location_Name FROM campus_student stu JOIN campus_student_classdetails cscd ON cscd.student_id_int = stu.student_id_int JOIN campus_classdetail cl ON cl.classdetail_id_int = cscd.classdetail_id_int JOIN campus_classsection se ON se.classsection_id_int = cscd.classsection_id_int JOIN campus_parentchildrelation re ON re.stu_addmissionNo = stu.student_id_int JOIN campus_parents par ON par.ParentID = re.parentid JOIN campus_location loc ON loc.Location_Id = stu.locationId WHERE stu.student_status_var='active' AND cscd.student_status='STUDYING' AND stu.student_dob_var LIKE ? ORDER BY CAST(SUBSTR(cscd.classdetail_id_int,4) AS UNSIGNED),CAST(SUBSTR(cscd.classsection_id_int,4) AS UNSIGNED),studentName";

	public static final String GET_LATECOMERS_LIST_SEARCH ="SELECT DISTINCT lcs.Late_Comers_Code,lcs.Date,cl.Location_Name,CONCAT(cs.student_fname_var,' ',cs.student_lname_var)AS studentname,ccd.classdetails_name_var,ccs.classsection_name_var,lcs.Description FROM latecomers_sms lcs JOIN campus_location cl ON cl.Location_Id=lcs.LocId  JOIN campus_classdetail ccd ON ccd.classdetail_id_int=lcs.Class_Code JOIN campus_classsection ccs ON ccs.classsection_id_int=lcs.Section_Code JOIN campus_student_classdetails csc ON (csc.classdetail_id_int=lcs.Class_Code AND csc.classsection_id_int= lcs.Section_Code) JOIN campus_student cs ON cs.student_id_int=lcs.Student_Code JOIN campus_acadamicyear cay ON cay.acadamic_id=lcs.AccyearId WHERE `LocId` like ? AND `Class_Code` like ? AND `Section_Code` like ? AND `AccyearId`=? and lcs.Date BETWEEN ? AND ?";

	public static final String SAVE_OTHER_SMS = "Insert into sms_any_other_sms (OtherSMS_Code,Student_Code,Class_Code,Section_Code,Date,Description,`academicYear`,locId,`createdby`) values(?,?,?,?,?,?,?,?,?)";

	public static final String GET_MEETING_LIST_FILTER = "select sm.`meetingid`,sm.`meetingdate`,sm.`title`,sm.`starttime`,sm.`endtime`,ccl.`classdetails_name_var`,ccs.`classsection_name_var`,CONCAT(stu.`student_fname_var`,' ',stu.`student_lname_var`)as student,sa.`sms_status` from  `sms_meeting` sm join `campus_classdetail` ccl on ccl.`classdetail_id_int`=sm.`classid` and ccl.`locationId`= sm.`locId` join `campus_classsection` ccs on ccs.`classsection_id_int`=sm.`sectionid` and ccs.`locationId`= sm.`locId` join `campus_student` stu on stu.`student_id_int`=sm.`studentname` JOIN  `sms_audit` sa ON sa.`ServiceCode`=sm.`meetingid` where sm.`locId` like ? and sm.`classid` like ? and sm.`sectionid` like ? and `accyear`=? And sm.`title`=? and sm.`meetingdate` between ? and ?";

	public static final String GET_PHNO_FOR_BDAY_STAFF = "SELECT CONCAT(ct.FirstName)AS teacherName,ct.department,ct.designation,ct.mobileNo,ct.TeacherID,ct.Loc_ID FROM campus_teachers ct WHERE ct.isActive='Y' AND ct.dateofBirth LIKE ?";

	public static final String GET_PHNO_FOR_ABSENT_SMS = "SELECT att.`addmissionno`,att.`accId`,att.`locationId`,att.`attendence`,(CASE WHEN re.relationship='father' THEN par.mobileno WHEN re.relationship='mother' THEN par.student_mothermobileno_var WHEN re.relationship='guardian' THEN par.student_gardian_mobileno ELSE '1' END) AS student_contact_mobileno,cscd.`classdetail_id_int`,cscd.`classsection_id_int`,stu.locationId FROM `campus_attendence` att JOIN `campus_student_classdetails` cscd ON cscd.`student_id_int` = att.`addmissionno` AND `student_status`='STUDYING' JOIN `campus_parentchildrelation` re ON re.`stu_addmissionNo` = att.`addmissionno` JOIN `campus_parents` par ON par.`ParentID` = re.`parentid` WHERE att.`attendence`='Absent' AND att.`attendencedate`=?";

	public static final String GET_FEE_SMS_LIST = "SELECT DISTINCT st.`student_id_int`,CONCAT(st.`student_fname_var`,'',st.`student_lname_var`)AS studentname,ccs.`classdetails_name_var`,sec.`classsection_name_var`,sa.`sms_status`,csf.`date`,csf.`created_time`  FROM `campus_sms_fee` csf JOIN `campus_sms_feediv` cf ON cf.`sms_fee_divid`=csf.`fee_sms_id` JOIN `campus_sms_fee_students` cfs ON cfs.`sms_fee_id`=csf.`fee_sms_id` JOIN `campus_student` st ON st.`student_id_int`=cfs.`stu_id` JOIN `campus_student_classdetails` cscd ON cscd.`student_id_int`=st.`student_id_int`AND cscd.`locationId`=st.`locationId` AND cscd.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=cscd.`locationId` AND cl.`isActive`='Y' JOIN `campus_acadamicyear` ca ON ca.`acadamic_id`=csf.`accy_id` AND ca.`isActive`='Y' JOIN `campus_classdetail` ccs ON ccs.`classdetail_id_int`=cscd.`classdetail_id_int` AND ccs.`locationId`=cscd.`locationId` AND ccs.`isActive`='Y' JOIN `campus_classsection` sec ON sec.`classsection_id_int` =cscd.`classsection_id_int` AND sec.`locationId`=cscd.`locationId` AND sec.`isActive`='Y' JOIN  `sms_audit` sa ON sa.`ServiceCode`= cfs.`sms_fee_stuid` WHERE csf.`loc_id`=? AND `accy_id`=?";

	


	
	
	
	
	
}
