package com.centris.campus.util;

public class StudentAttendanceSqlUtil {

	//public static final String GET_ATTENDANCE_LIST = "select distinct s.specilization,s.classsection_id_int,s.classdetail_id_int,ta.AttendenceDate,count(s.student_id_int) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(FirstName,' ',LastName) as teachers,clt.TeacherCode,case when s.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where s.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta,campus_student s,campus_classdetail cls,campus_classsection sec,campus_teachers ct,campus_classteacher clt where ta.AttendenceDate between ? and ? and s.classdetail_id_int=cls.classdetail_id_int and clt.TeacherCode = ct.TeacherID and clt.ClassCode = s.classdetail_id_int and clt.SectionCode = s.classsection_id_int and s.classsection_id_int = sec.classsection_id_int  and s.student_id_int=ta.addmissionno group by ta.AttendenceDate,classsection";
	//public static final String GET_ATTENDANCE_LIST = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(csc.student_id_int) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(FirstName,' ',LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select spec.Specialization_name from campus_class_specialization spec where csc.specilization = spec.Specialization_Id and cls.classdetail_id_int = spec.ClassDetails_Id )end Specialization_name from campus_attendence ta left join campus_student_classdetails csc on csc.student_id_int=ta.addmissionno left join campus_teachers ct on ct.TeacherID=ta.addmissionno left join campus_classdetail cls on csc.classdetail_id_int=cls.classdetail_id_int left join campus_classsection sec on csc.classsection_id_int = sec.classsection_id_int left join campus_classteacher clt on clt.ClassCode = csc.classdetail_id_int and csc.classsection_id_int=sec.classsection_id_int and clt.TeacherCode = ct.TeacherID where ta.AttendenceDate between ? and ? group by ta.AttendenceDate,classsection";
	//public static final String GET_ATTENDANCE_LIST = "select distinct csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,ta.AttendenceDate,count(s.student_id_int) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(FirstName,' ',LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta,campus_student s join campus_student_classdetails csc on csc.student_id_int=s.student_id_int,campus_classdetail cls,campus_classsection sec,campus_teachers ct,campus_classteacher clt where ta.AttendenceDate between ? and ? and csc.classdetail_id_int=cls.classdetail_id_int and clt.TeacherCode = ct.TeacherID and clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.classsection_id_int = sec.classsection_id_int  and s.student_id_int=ta.addmissionno group by ta.AttendenceDate,classsection";
	//public static final String GET_ATTENDANCE_LIST = "select distinct csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,ta.AttendenceDate,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,count(s.student_id_int) as total_streangth,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_student s on s.student_id_int=ta.addmissionno left join campus_student_classdetails csc on csc.student_id_int=s.student_id_int left join campus_classdetail cls on csc.classdetail_id_int=cls.classdetail_id_int left join campus_classsection sec on csc.classsection_id_int = sec.classsection_id_int left outer join campus_classteacher clt on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int left outer join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.AttendenceDate between ? and ? group by ta.AttendenceDate,classsection";
	public static final String GET_ATTENDANCE_LIST = "SELECT a.`attendencedate`,COUNT(sa.`stud_id`)AS total_streangth,SUM(CASE WHEN sa.`atten_status`='Present' THEN 1 ELSE 0 END) TotalPresent,SUM(CASE WHEN sa.`atten_status`='Absent' THEN 1 ELSE 0 END) TotalAbsent,SUM(CASE WHEN sa.`atten_status`='Leave' THEN 1 ELSE 0 END) Totalleave ,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,CONCAT(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection FROM `campus_attendence` a  JOIN  `campus_student_attenstatus` sa ON sa.`attendance_id`=a.`attend_id`JOIN`campus_student`  s ON s.`student_id_int`=sa.`stud_id` JOIN campus_student_classdetails csc ON csc.`student_id_int`=s.`student_id_int`AND csc.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=csc.`locationId`AND cl.`isActive` ='Y' JOIN  `campus_acadamicyear`ca ON ca.`acadamic_id`=csc.`fms_acadamicyear_id_int` AND ca.`isActive`='Y' JOIN `campus_classdetail` cls ON cls.`classdetail_id_int`=csc.`classdetail_id_int` AND cls.`isActive`='Y' AND cls.`locationId`= csc.`locationId` JOIN `campus_classsection` sec ON sec.`classsection_id_int`=csc.`classsection_id_int` AND sec.`locationId`=csc.`locationId`AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id` =csc.`specilization`AND spl.`isActive`='Y' AND spl.`locationId`= csc.`locationId` WHERE a.AttendenceDate BETWEEN ? AND ? AND a.specializationId='-'";

	//public static final String GET_STUDENT_ATTENDANCE_LIST = "select s.student_id_int,s.student_admissionno_var,concat(s.student_fname_var,' ',s.student_lname_var) studentname,cd.classdetails_name_var,se.classsection_name_var,case when a.attendence is null then 'Present' else a.attendence end status,case when period1 is null then 'Present' else period1 end period1Status,case when period2 is null then 'Present' else period2 end period2Status,case when period3 is null then 'Present' else period3 end period3Status,case when period4 is null then 'Present' else period4 end period4Status,case when period5 is null then 'Present' else period5 end period5Status,case when period6 is null then 'Present' else period6 end period6Status,case when period7 is null then 'Present' else period7 end period7Status,case when period8 is null then 'Present' else period8 end period8Status,case when period9 is null then 'Present' else period9 end period9Status from  campus_student s left outer join campus_attendence a on a.addmissionno=s.student_id_int and a.attendencedate=?,campus_classdetail cd,campus_classsection se  where s.classdetail_id_int=cd.classdetail_id_int and s.classsection_id_int=se.classsection_id_int and s.classdetail_id_int like ? and s.classsection_id_int like ? order by length(s.student_admissionno_var),s.student_admissionno_var";
	//public static final String GET_STUDENT_ATTENDANCE_LIST ="select distinct s.student_id_int,s.student_admissionno_var,concat(s.student_fname_var,' ',s.student_lname_var) studentname,cd.classdetails_name_var,se.classsection_name_var,case when a.attendence is null then 'Present' else a.attendence end status,case when period1 is null then 'Present' else period1 end period1Status,case when period2 is null then 'Present' else period2 end period2Status,case when period3 is null then 'Present' else period3 end period3Status,case when period4 is null then 'Present' else period4 end period4Status,case when period5 is null then 'Present' else period5 end period5Status,case when period6 is null then 'Present' else period6 end period6Status,case when period7 is null then 'Present' else period7 end period7Status,case when period8 is null then 'Present' else period8 end period8Status,case when period9 is null then 'Present' else period9 end period9Status from  campus_student s left outer join campus_attendence a on a.addmissionno=s.student_id_int and a.attendencedate=? left join campus_student_classdetails csc on csc.student_id_int=s.student_id_int,campus_classdetail cd,campus_classsection se  where csc.classdetail_id_int=cd.classdetail_id_int and csc.classsection_id_int=se.classsection_id_int and csc.classdetail_id_int like ? and csc.classsection_id_int like ? order by length(s.student_admissionno_var),s.student_admissionno_var";


	public static final String GET_STUDENT_ATTENDANCE_LIST ="SELECT sa.`stud_id`,sa.`atten_status`as status,GROUP_CONCAT(`periods` ORDER BY CAST(SUBSTRING(`periods`,7,LENGTH(`periods`)-6) AS SIGNED))AS periods ,GROUP_CONCAT(`period_status` ORDER BY CAST(SUBSTRING(`periods`,7,LENGTH(`periods`)-6) AS SIGNED))AS periodstatus,s.`student_admissionno_var`,CONCAT(s.student_fname_var,' ',s.student_lname_var) studentname,att.attend_id,sa.status_id FROM `campus_attendence` att JOIN `campus_student_attenstatus` sa ON att.`attend_id` = sa.`attendance_id` JOIN `campus_period_attendance` pa ON pa.`staus_id` =sa.`status_id` JOIN `campus_student_classdetails` stu ON stu.`student_id_int`= sa.`stud_id` AND stu.`student_status`='STUDYING' JOIN `campus_student` s ON s.`student_id_int` = stu.`student_id_int`JOIN `campus_location` cl ON cl.`Location_Id`=att.`locationId` AND cl.`isActive`='Y' JOIN `campus_acadamicyear` ca ON ca.`acadamic_id`=att.`accId` AND ca.`isActive`='Y' JOIN `campus_classdetail` cd ON cd.`classdetail_id_int`=att.`class_id` AND cd.`isActive`='Y' AND cd.`locationId` = att.`locationId` JOIN `campus_classsection` sec ON sec.`classsection_id_int` =att.`sec_id` AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id`=att.`specializationId` AND spl.`isActive`='Y'WHERE `attendencedate` =? AND att.`class_id` LIKE ? AND att.`sec_id` LIKE ? AND att.`specializationId`='-' AND att.`accId`=? GROUP BY pa.`staus_id`";

	//public static final String GET_SPEC_STUDENT_ATTENDANCE_LIST = "select s.student_id_int,s.student_admissionno_var,concat(s.student_fname_var,' ',s.student_lname_var) studentname,cd.classdetails_name_var,se.classsection_name_var,case when a.attendence is null then 'Present' else a.attendence end status,case when period1 is null then 'Present' else period1 end period1Status,case when period2 is null then 'Present' else period2 end period2Status,case when period3 is null then 'Present' else period3 end period3Status,case when period4 is null then 'Present' else period4 end period4Status,case when period5 is null then 'Present' else period5 end period5Status,case when period6 is null then 'Present' else period6 end period6Status,case when period7 is null then 'Present' else period7 end period7Status,case when period8 is null then 'Present' else period8 end period8Status,case when period9 is null then 'Present' else period9 end period9Status from  campus_student s left outer join campus_attendence a on a.addmissionno=s.student_id_int and a.attendencedate=?,campus_classdetail cd,campus_classsection se  where s.classdetail_id_int=cd.classdetail_id_int and s.classsection_id_int=se.classsection_id_int and s.classdetail_id_int like ? and s.classsection_id_int like ? and specilization like ? order by length(s.student_admissionno_var),s.student_admissionno_var";
	public static final String GET_SPEC_STUDENT_ATTENDANCE_LIST = "SELECT sa.`stud_id`,sa.`atten_status` as status ,GROUP_CONCAT(`periods` ORDER BY CAST(SUBSTRING(`periods`,7,LENGTH(`periods`)-6) AS SIGNED))AS periods ,GROUP_CONCAT(`period_status` ORDER BY CAST(SUBSTRING(`periods`,7,LENGTH(`periods`)-6) AS SIGNED))AS periodstatus,s.`student_admissionno_var`,CONCAT(s.student_fname_var,' ',s.student_lname_var) studentname,att.attend_id,sa.status_id  FROM `campus_attendence` att JOIN `campus_student_attenstatus` sa ON att.`attend_id` = sa.`attendance_id` JOIN `campus_period_attendance` pa ON pa.`staus_id` =sa.`status_id` JOIN `campus_student_classdetails` stu ON stu.`student_id_int`= sa.`stud_id` AND stu.`student_status`='STUDYING' JOIN `campus_student` s ON s.`student_id_int` = stu.`student_id_int`JOIN `campus_location` cl ON cl.`Location_Id`=att.`locationId` AND cl.`isActive`='Y' JOIN `campus_acadamicyear` ca ON ca.`acadamic_id`=att.`accId` AND ca.`isActive`='Y' JOIN `campus_classdetail` cd ON cd.`classdetail_id_int`=att.`class_id` AND cd.`isActive`='Y' AND cd.`locationId` = att.`locationId` JOIN `campus_classsection` sec ON sec.`classsection_id_int` =att.`sec_id` AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id`=att.`specializationId` AND spl.`isActive`='Y'WHERE `attendencedate` =? AND att.`class_id` LIKE ? AND att.`sec_id` LIKE ? AND att.`specializationId` like ? AND att.`accId`=? GROUP BY pa.`staus_id`"; 

	public static final String GET_ATTENDANCE_COUNT = "SELECT COUNT(*) FROM campus_attendence WHERE `attendencedate`=? AND `locationId`=? AND `class_id`=? AND `sec_id` =?";

	public static final String UPDATE_ATTENDANCE = "update campus_attendence set attendence=?,updatedBy=?,updateDate=?,period1=?,period2=?,period3=?,period4=?,period5=?,period6=?,period7=?,period8=?,period9=? where  addmissionno=? and attendencedate=?"; /*,accId=?*/

	public static final String INSERT_ATTENDANCE ="INSERT INTO campus_attendence(attendencedate,createdBy,CreateDate,teacherId,locationId,accId,specializationId,`class_id`,`sec_id`) VALUES(?,?,?,?,?,?,?,?,?)";

	public static final String GET_STU_PERIOD_ATT ="select * from campus_student_period_attendance where AttendanceDate=? and StudentId=?";

	public static final String UPDATE_STU_PERIOD_ATT = "update campus_student_period_attendance set  Period1=?,Period2=?,Period3=?,Period4=?,Period5=?,Period6=?,Period7=?,Period8=?,UpdatedBy=?,UpdateDate=? where AttendanceDate=? and StudentId=?";

	public static final String INSERT_STU_PERIOD_ATT = "insert into campus_student_period_attendance(AttendanceDate,StudentId,Period1,Period2,Period3,Period4,Period5,Period6,Period7,Period8,CreatedBy,CreateDate) values(?,?,?,?,?,?,?,?,?,?,?,?)";

	public static final String CHECK_STU_PERIOD_ATT = "select count(*) from campus_student_period_attendance where AttendanceDate=? and StudentId=?";

	public static final String GET_TEACHERBY_CLASS = "select concat(FirstName,' ',LastName) as teacher,TeacherID from campus_teachers,campus_classteacher where TeacherCode = TeacherID and ClassCode = ? and SectionCode = ?";

	public static final String GET_SEARCH_ATTENDANCE_LIST = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.locationId like ? and ta.AttendenceDate>=? and ta.AttendenceDate<=? group by ta.AttendenceDate,classsection";

	public static final String GET_CLASS_ATTENDANCE_LIST = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.locationId like ? and clt.ClassCode like ? group by ta.AttendenceDate,classsection";

	public static final String GET_CLASS_SECTION_ATTENDANCE_LIST ="SELECT a.`accId`,a.`locationId`,a.`attendencedate`,COUNT(sa.`stud_id`)AS total_streangth,SUM(CASE WHEN sa.`atten_status`='Present' THEN 1 ELSE 0 END) TotalPresent,SUM(CASE WHEN sa.`atten_status`='Absent' THEN 1 ELSE 0 END) TotalAbsent,SUM(CASE WHEN sa.`atten_status`='Leave' THEN 1 ELSE 0 END) Totalleave ,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,CONCAT(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,spl.`Specialization_name`FROM `campus_attendence` a  JOIN  `campus_student_attenstatus` sa ON sa.`attendance_id`=a.`attend_id`JOIN`campus_student`  s ON s.`student_id_int`=sa.`stud_id` JOIN campus_student_classdetails csc ON csc.`student_id_int`=s.`student_id_int` AND csc.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=csc.`locationId` AND cl.`isActive` ='Y' JOIN  `campus_acadamicyear`ca ON ca.`acadamic_id`=csc.`fms_acadamicyear_id_int` AND ca.`isActive`='Y' JOIN `campus_classdetail` cls ON cls.`classdetail_id_int`=csc.`classdetail_id_int` AND cls.`isActive`='Y' AND cls.`locationId`= csc.`locationId`JOIN `campus_classsection` sec ON sec.`classsection_id_int`=csc.`classsection_id_int` AND sec.`locationId`=csc.`locationId`AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id` =csc.`specilization`AND spl.`isActive`='Y' AND spl.`locationId`= csc.`locationId` WHERE a.`specializationId` like ?  and  a.`locationId` LIKE ? AND a.`accId` like ? AND `class_id` LIKE ? AND a.`sec_id` LIKE ? "; 

	public static final String GET_TEACHER_LIST = "select TeacherID,concat(FirstName,' ',LastName) as teachername from campus_teachers where Loc_ID like ? order by teachername";

	public static final String GET_ATTENDANCE_LIST_BY_TEACHER = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.locationId like ? and clt.ClassCode like ? and clt.SectionCode like ? and clt.TeacherCode like ? group by ta.AttendenceDate,classsection";

	public static final String GET_ACADAMICYEAR_DATE = "select startDate,endDate from campus_acadamicyear where acadamic_id=?";

	public static final String GET_ATTENDANCE_LIST_BY_DATE = "select ta.AttendenceDate,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,count(ta.addmissionno) as total_streangth,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,sum(case when ta.attendence='Present' then 1 else 0 end) TotalPresent,sum(case when ta.attendence='Absent' then 1 else 0 end) TotalAbsent,sum(case when ta.attendence='Holiday' then 1 else 0 end) TotalHoliday,sum(case when ta.attendence='Leave' then 1 else 0 end) Totalleave,concat(ct.FirstName,' ',ct.LastName) as teachers,clt.TeacherCode,case when csc.specilization = '-' then  '-' else (select Specialization_name from campus_class_specialization  where csc.specilization = Specialization_Id and cls.classdetail_id_int = ClassDetails_Id )end Specialization_name from campus_attendence ta join campus_classteacher clt on clt.TeacherCode=ta.teacherId and ta.locationId=clt.locationId join campus_student_classdetails csc on clt.ClassCode = csc.classdetail_id_int and clt.SectionCode = csc.classsection_id_int and csc.student_id_int=ta.addmissionno and csc.locationId=clt.locationId join campus_classdetail cls on clt.ClassCode = cls.classdetail_id_int and clt.locationId=cls.locationId join campus_classsection sec on clt.SectionCode = sec.classsection_id_int and clt.locationId=sec.locationId join campus_teachers ct on clt.TeacherCode = ct.TeacherID where ta.AttendenceDate between ? and ? group by ta.AttendenceDate,classsection";

	public static final String GET_CLASS_SECTION_ATTENDANCE_LIST_BY_DATE = "SELECT a.`accId`,a.`locationId`,a.`attendencedate`,COUNT(sa.`stud_id`)AS total_streangth,SUM(CASE WHEN sa.`atten_status`='Present' THEN 1 ELSE 0 END) TotalPresent,SUM(CASE WHEN sa.`atten_status`='Absent' THEN 1 ELSE 0 END) TotalAbsent,SUM(CASE WHEN sa.`atten_status`='Leave' THEN 1 ELSE 0 END) Totalleave ,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,CONCAT(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,spl.`Specialization_name` FROM `campus_attendence` a  JOIN  `campus_student_attenstatus` sa ON sa.`attendance_id`=a.`attend_id`JOIN`campus_student`  s ON s.`student_id_int`=sa.`stud_id` JOIN campus_student_classdetails csc ON csc.`student_id_int`=s.`student_id_int` AND csc.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=csc.`locationId`AND cl.`isActive` ='Y' JOIN  `campus_acadamicyear`ca ON ca.`acadamic_id`=csc.`fms_acadamicyear_id_int` AND ca.`isActive`='Y' JOIN `campus_classdetail` cls ON cls.`classdetail_id_int`=csc.`classdetail_id_int` AND cls.`isActive`='Y' AND cls.`locationId`= csc.`locationId` JOIN `campus_classsection` sec ON sec.`classsection_id_int`=csc.`classsection_id_int` AND sec.`locationId`=csc.`locationId`AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id` =csc.`specilization` AND spl.`isActive`='Y' AND spl.`locationId`= csc.`locationId` WHERE a.`specializationId` LIKE ? a.`locationId` LIKE ? AND a.`accId` LIKE ? AND `class_id` LIKE ? AND a.`sec_id` LIKE ? AND a.`attendencedate` BETWEEN ? AND ?";

	public static final String GET_CLASS_SECTION_ATTENDANCE_LIST_BY_SPECIALIZATION ="SELECT a.`accId`,a.`locationId`,a.`attendencedate`,COUNT(sa.`stud_id`)AS total_streangth,SUM(CASE WHEN sa.`atten_status`='Present' THEN 1 ELSE 0 END) TotalPresent,SUM(CASE WHEN sa.`atten_status`='Absent' THEN 1 ELSE 0 END) TotalAbsent,SUM(CASE WHEN sa.`atten_status`='Leave' THEN 1 ELSE 0 END) Totalleave ,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,CONCAT(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,CASE WHEN spl.`Specialization_name` IS NULL THEN '-' WHEN spl.`Specialization_name`='' THEN '-'ELSE spl.`Specialization_name` END `Specialization_name`FROM `campus_attendence` a JOIN `campus_student_attenstatus` sa ON sa.`attendance_id`=a.`attend_id` JOIN `campus_student` s ON s.`student_id_int`=sa.`stud_id` JOIN campus_student_classdetails csc ON csc.`student_id_int`=s.`student_id_int` AND csc.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=csc.`locationId` AND cl.`isActive` ='Y' JOIN `campus_acadamicyear`ca ON ca.`acadamic_id`=csc.`fms_acadamicyear_id_int` AND ca.`isActive`='Y' JOIN `campus_classdetail` cls ON cls.`classdetail_id_int`=csc.`classdetail_id_int` AND cls.`isActive`='Y' AND cls.`locationId`= csc.`locationId` JOIN `campus_classsection` sec ON sec.`classsection_id_int`=csc.`classsection_id_int` AND sec.`locationId`=csc.`locationId` AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id` =csc.`specilization` AND spl.`isActive`='Y' AND spl.`locationId`= csc.`locationId` AND spl.`Specialization_Id` LIKE ? WHERE a.`locationId`=? AND a.`accId` = ? AND `class_id` LIKE ? AND a.`sec_id` LIKE ? GROUP BY a.`class_id`,a.`sec_id`,a.`attendencedate` ORDER BY  a.`attendencedate` DESC,CAST(SUBSTRING(a.`class_id`,4,LENGTH(a.`class_id`)-3) AS SIGNED)";

	public static final String GET_CLASS_SECTION_ATTENDANCE_LIST_BY_DATE_BY_SPECIALIZATION = "SELECT a.`accId`,a.`locationId`,a.`attendencedate`,COUNT(sa.`stud_id`)AS total_streangth,SUM(CASE WHEN sa.`atten_status`='Present' THEN 1 ELSE 0 END) TotalPresent,SUM(CASE WHEN sa.`atten_status`='Absent' THEN 1 ELSE 0 END) TotalAbsent,SUM(CASE WHEN sa.`atten_status`='Leave' THEN 1 ELSE 0 END) Totalleave ,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,CONCAT(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection,CASE WHEN spl.`Specialization_name` IS NULL THEN '-' WHEN spl.`Specialization_name`='' THEN '-'ELSE spl.`Specialization_name` END `Specialization_name` FROM `campus_attendence` a  JOIN  `campus_student_attenstatus` sa ON sa.`attendance_id`=a.`attend_id`JOIN`campus_student`  s ON s.`student_id_int`=sa.`stud_id` JOIN campus_student_classdetails csc ON csc.`student_id_int`=s.`student_id_int` AND csc.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=csc.`locationId`AND cl.`isActive` ='Y' JOIN  `campus_acadamicyear`ca ON ca.`acadamic_id`=csc.`fms_acadamicyear_id_int` AND ca.`isActive`='Y' JOIN `campus_classdetail` cls ON cls.`classdetail_id_int`=csc.`classdetail_id_int` AND cls.`isActive`='Y' AND cls.`locationId`= csc.`locationId` JOIN `campus_classsection` sec ON sec.`classsection_id_int`=csc.`classsection_id_int` AND sec.`locationId`=csc.`locationId`AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id` =csc.`specilization` AND spl.`isActive`='Y' AND spl.`locationId`= csc.`locationId` AND spl.`Specialization_Id` LIKE ? WHERE a.`locationId`=? AND a.`accId` = ? AND `class_id` LIKE ? AND a.`sec_id` LIKE ? AND a.`attendencedate` BETWEEN ? AND ? GROUP BY a.`class_id`,a.`sec_id`,a.`attendencedate` ORDER BY  a.`attendencedate` DESC, CAST(SUBSTRING(a.`class_id`,4,LENGTH(a.`class_id`)-3) AS SIGNED)";

	public static final String GET_STUDENT_COUNT_ACADEMIC_YEAR = "SELECT `Location_Name`,`acadamic_year` , COUNT(`student_id_int`) AS Total  FROM  `campus_student_classdetails`  sc JOIN  `campus_acadamicyear` ac ON sc.`fms_acadamicyear_id_int` = ac.`acadamic_id` AND ac.`isActive` = 'Y' JOIN `campus_location` l ON  l.`isActive` = 'Y' AND l.`Location_Id` = sc.`locationId` WHERE sc.`locationId` = ? AND sc.student_status='STUDYING'  GROUP BY ac.`acadamic_id` ORDER BY `startDate`";

	public static final String GET_TODAY_STUDENT_ATTENDANCE = "SELECT (SELECT COUNT(*) FROM  `campus_student_classdetails` WHERE  `fms_acadamicyear_id_int` = ? AND `student_status` = 'studying' AND `locationId` = ?) AS Total,COALESCE(SUM(CASE WHEN `atten_status` = 'Present' THEN 1 ELSE 0 END ),0) AS Present , COALESCE(SUM(CASE WHEN `atten_status` = 'absent' THEN 1 ELSE 0 END ),0) AS Absent , COALESCE(SUM(CASE WHEN `atten_status` = 'leave' THEN 1 ELSE 0 END ),0) AS `leave` FROM `campus_attendence` a   JOIN `campus_location` l ON l.`Location_Id` = a.`locationId` JOIN `campus_student_attenstatus` sa ON sa.`attendance_id` = a.`attend_id` JOIN `campus_acadamicyear` ay  ON  ay.`acadamic_id`  =  a.`accId`  WHERE  a.`locationId` = ? AND a.`accId` = ? AND  a.`attendencedate` = ? ";

	//"SELECT (SELECT COUNT(*) FROM `campus_student_classdetails` WHERE `fms_acadamicyear_id_int` = ? AND `locationId` like ?) AS Total , COALESCE(SUM(CASE WHEN `attendence` = 'Present' THEN 1 ELSE 0 END ),0) AS Present ,  COALESCE(SUM(CASE WHEN `attendence` = 'absent' THEN 1 ELSE 0 END ),0) AS Absent , COALESCE(SUM(CASE WHEN `attendence` = 'leave' THEN 1 ELSE 0 END ),0) AS `leave` FROM `campus_attendence` a   JOIN `campus_location` l ON l.`Location_Id` = a.`locationId` JOIN `campus_acadamicyear` ay  ON  ay.`acadamic_id`  =  a.`accId`  WHERE  a.`locationId` = ? AND a.`accId` = ? AND  a.`attendencedate` = ? ";

	public static final String GET_CLASS_WISE_STUDENT = "SELECT `classdetails_name_var`,cd.`classdetail_id_int`,COUNT(`student_id_int`) AS Total FROM `campus_classdetail` cd   LEFT JOIN `campus_student_classdetails` s ON cd.`classdetail_id_int` = s.`classdetail_id_int` AND s.`student_status` = 'STUDYING' AND `fms_acadamicyear_id_int` = ? AND s.`locationId` = cd. `locationId` LEFT JOIN `campus_classstream` cls ON  cls.`locationId` = cd.`locationId` AND cls.`isActive` = 'Y' AND cls.`classstream_id_int` = s.`fms_classstream_id_int`   WHERE cd.`locationId` = ? GROUP BY cd.`classdetail_id_int`  ORDER BY CAST(SUBSTRING(cd.`classdetail_id_int`,4,LENGTH(cd.`classdetail_id_int`)-3) AS SIGNED) ";

	//"SELECT `classdetails_name_var` , COALESCE(COUNT(`student_id_int`),0) AS Total  FROM `campus_student_classdetails` sc  JOIN `campus_classdetail` cd ON cd.`classdetail_id_int` = sc.`classdetail_id_int` AND sc.`locationId` = cd.`locationId` WHERE sc.`locationId` like ? AND sc.`fms_acadamicyear_id_int` = ?  AND sc.student_status = 'studying'  GROUP BY sc.`classdetail_id_int` ORDER BY CAST(SUBSTRING(sc.`classdetail_id_int`,4,LENGTH(sc.`classdetail_id_int`)-3) AS SIGNED) ";

	public static final String GET_STUDENT_ATTENDANCE_LIST_ADD = "SELECT DISTINCT s.`student_id_int`, s.`student_admissionno_var`,CONCAT (s.`student_fname_var`,' ',s.`student_lname_var`)studentname  FROM `campus_student` s JOIN campus_student_classdetails csc ON csc.`student_id_int`=s.`student_id_int` AND csc.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=csc.`locationId` AND cl.`isActive` ='Y' JOIN  `campus_acadamicyear`ca ON ca.`acadamic_id`=csc.`fms_acadamicyear_id_int` AND ca.`isActive`='Y' JOIN `campus_classdetail` cls ON cls.`classdetail_id_int`=csc.`classdetail_id_int` AND cls.`isActive`='Y' AND cls.`locationId`= csc.`locationId`JOIN `campus_classsection` sec ON sec.`classsection_id_int`=csc.`classsection_id_int` AND sec.`locationId`=csc.`locationId`AND sec.`isActive`='Y' WHERE s.student_status_var = 'active' AND csc.classdetail_id_int LIKE ? AND csc.classsection_id_int LIKE ? AND csc.fms_acadamicyear_id_int=? AND csc.`locationId` like ? ORDER BY studentname,LENGTH(s.student_admissionno_var),s.student_admissionno_var";

	public static final String GET_SPEC_STUDENT_ATTENDANCE_LIST_ADD = "SELECT DISTINCT s.`student_id_int`, s.`student_admissionno_var`,CONCAT (s.`student_fname_var`,' ',s.`student_lname_var`)studentname  FROM `campus_student`  s JOIN campus_student_classdetails csc ON csc.`student_id_int`=s.`student_id_int` AND csc.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=csc.`locationId` AND cl.`isActive` ='Y' JOIN  `campus_acadamicyear`ca ON ca.`acadamic_id`=csc.`fms_acadamicyear_id_int` AND ca.`isActive`='Y' JOIN `campus_classdetail` cls ON cls.`classdetail_id_int`=csc.`classdetail_id_int` AND cls.`isActive`='Y' AND cls.`locationId`= csc.`locationId`JOIN `campus_classsection` sec ON sec.`classsection_id_int`=csc.`classsection_id_int` AND sec.`locationId`=csc.`locationId`AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id` =csc.`specilization`AND spl.`isActive`='Y' AND spl.`locationId`= csc.`locationId` WHERE s.student_status_var = 'active' AND csc.classdetail_id_int LIKE ? AND csc.classsection_id_int LIKE ? AND csc.specilization LIKE ? AND csc.fms_acadamicyear_id_int=? AND csc.`locationId` like ? ORDER BY studentname,LENGTH(s.student_admissionno_var),s.student_admissionno_var";

	public static final String GET_LIST_OF_STUDENT_ATTENDENCE = "SELECT a.`attendencedate`,COUNT(sa.`stud_id`)AS total_streangth,SUM(CASE WHEN sa.`atten_status`='Present' THEN 1 ELSE 0 END) TotalPresent,SUM(CASE WHEN sa.`atten_status`='Absent' THEN 1 ELSE 0 END) TotalAbsent,SUM(CASE WHEN sa.`atten_status`='Leave' THEN 1 ELSE 0 END) Totalleave ,csc.specilization,csc.classsection_id_int,csc.classdetail_id_int,CONCAT(cls.classdetails_name_var,'-',sec.classsection_name_var) classsection FROM `campus_attendence` a JOIN `campus_student_attenstatus` sa ON sa.`attendance_id`=a.`attend_id` JOIN `campus_student` s ON s.`student_id_int`=sa.`stud_id` JOIN campus_student_classdetails csc ON csc.`student_id_int`=s.`student_id_int`AND csc.`student_status`='STUDYING' JOIN `campus_location` cl ON cl.`Location_Id`=csc.`locationId`AND cl.`isActive` ='Y' JOIN `campus_acadamicyear`ca ON ca.`acadamic_id`=csc.`fms_acadamicyear_id_int` AND ca.`isActive`='Y' JOIN `campus_classdetail` cls ON cls.`classdetail_id_int`=csc.`classdetail_id_int` AND cls.`isActive`='Y' AND cls.`locationId`= csc.`locationId` JOIN `campus_classsection` sec ON sec.`classsection_id_int`=csc.`classsection_id_int` AND sec.`locationId`=csc.`locationId` AND sec.`isActive`='Y' LEFT JOIN `campus_class_specialization` spl ON spl.`Specialization_Id` =csc.`specilization` AND spl.`isActive`='Y' AND spl.`locationId`= csc.`locationId` WHERE a.AttendenceDate BETWEEN ? AND ? AND a.specializationId=?";

	public static final String INSERT_SMSFEE = "INSERT INTO `campus_sms_fee`(`loc_id`,`accy_id`,`class_id`,`term_id`,`template`,`date`,`created_by`)VALUES(?,?,?,?,?,?,?)";

	public static final String INSERT_SMSFEE_DIV = "INSERT INTO `campus_sms_feediv` (`sms_fee_divid`,`sec_id`)VALUES(?,?)";

}


