package com.centris.campus.util;

public class SubjectSqlUtils {
	
	//public static final String VIEW_SUBJECT_DETAILS="select DISTINCT cs.specialization,cs.locationId,cl.Location_Name,cs.subjectID ,cs.subjectName,cs.syllabous,cs.decription,cd.classdetails_name_var,case when cs.remark is null then '' when cs.remark =''then '' else cs.remark end remark,cs.Sub_Code  from campus_subject cs ,campus_classdetail cd,campus_location cl where  cs.locationId=cl.Location_Id and cl.isActive='Y' and cs.classid=cd.classdetail_id_int and cd.`locationId` = cs.locationId and cs.status='active' and cs.locationId like ? and cs.isActive='Y' order by CAST(SUBSTRING(classid,4,LENGTH(classid-3))AS SIGNED),cs.subjectName"; 
	public static final String VIEW_SUBJECT_DETAILS="SELECT DISTINCT CASE WHEN cs.specialization='' THEN '-' WHEN cs.specialization IS NULL THEN '-' ELSE cs.specialization END specialization ,cs.locationId,cl.Location_Name,cs.subjectID ,cs.subjectName,cs.syllabous,cs.decription,cd.classdetails_name_var,CASE WHEN cs.remark IS NULL THEN '' WHEN cs.remark =''THEN '' ELSE cs.remark END remark,cs.Sub_Code FROM campus_subject cs ,campus_classdetail cd,campus_location cl WHERE  cs.locationId=cl.Location_Id AND cl.isActive='Y' AND cs.classid=cd.classdetail_id_int AND cd.`locationId` = cs.locationId AND cs.`isActive` = 'Y' AND cd.`isActive` = 'Y' AND cs.locationId LIKE ? AND cs.isActive='Y' ORDER BY CAST(SUBSTRING(classid,4,LENGTH(classid-3))AS SIGNED),cs.subjectName";  
    public static final String DELETE_SUBJECT_DETAILS="update campus_subject set isActive=?, remark =? where subjectID=? and locationId=?";
    public static final String SEARCH_SUBJECT_DETAILS="select DISTINCT ccsp.Specialization_name,cl.Location_Name,s.*,cd.classdetails_name_var,s.subjectCode from campus_subject s,campus_classdetail cd,campus_location cl,campus_class_specialization ccsp where s.locationId=cl.Location_Id and isActive='Y' and s.specialization=ccsp.Specialization_Id and (cl.Location_Name like ? or cd.classdetails_name_var like ? or ccsp.Specialization_name like ? or s.subjectName like ? or s.subjectCode like ?  ) and s.classid=cd.classdetail_id_int and s.locationId like ? and isActive='Y'";
    public static final String INSERT_ADDSUBJECT_FORM = "insert into campus_subject(subjectID,subjectName,classid,decription,createdby,locationId,specialization,Sub_Code,isLanguage,isLab,subType,createdtime) values(?,?,?,?,?,?,?,?,?,?,?,now())";
    public static final String GET_SINGLE_SUBJECT_DETAILS="select * from campus_subject  where subjectID=?";
    public static final String UPDATE_SUBJECT = "update campus_subject set subjectName=?,classid=?, decription=?, updateby=? ,updatedtime=?, isLab=?, subType=?,locationId=?,specialization=?,isLanguage=?,Sub_Code=? where subjectID=?";
    public static final String VALIDATE_CLASS_SUBJECT = "select count(*) count from campus_subject where subjectName=? and classid=? and locationId = ?";
    public static final String ViewAllSubjectsPath = "select * from campus_subject where subjectID=?";
    public static final String GET_SYLLABUS_PATH = "select syllabous,subjectName from campus_subject where subjectID=?";
    public static final String GET_ISSUED_FORM_DETAILS="select concat(student_first_name,student_last_name) as studentname,email,mobile_number,address,stu_parrelationship,stream_id,class_id,parents_name from campus_parent_enquiry_details where enquiry_id=?";
	public static final String VIEW_LAB_DETAILS = "SELECT l.`Location_Name` , cd.`classdetails_name_var` , sub.`subjectName` , ld.lab_id,Lab_Name,CASE WHEN spe.Specialization_name IS NULL THEN 'General' ELSE spe.Specialization_name END Specialization_name ,ld.Lab_Code,ld.Description FROM laboratory_details ld JOIN   `campus_subject`  sub ON  sub.`subjectID` = ld.`Subject` AND sub.isActive='Y'  AND sub.locationId = ld.`School_Name` AND  sub.isLab='Y' JOIN  `campus_location` l  ON  l.`Location_Id` = ld.`School_Name` AND l.isActive = 'Y' JOIN  `campus_classdetail` cd ON cd.`classdetail_id_int` = ld.`Class_Name`  AND cd.isActive='Y' AND cd.`locationId` = ld.School_Name LEFT JOIN campus_class_specialization spe ON spe.Specialization_Id = ld.Specialization  WHERE  cd.locationId = ld.School_Name ORDER BY LENGTH(cd.classdetail_id_int),cd.classdetail_id_int,spe.Specialization_name,ld.Lab_Name ";
	public static final String VALIDATE_CLASS_LAB = "select count(*) count from campus_subject where subjectName=? and classid=?";
	public static final String INSERT_LAB_FORM = "INSERT INTO laboratory_details(lab_id,School_Name,Class_Name,SUBJECT,Lab_Name,Specialization,Description,Lab_Code,status) VALUES(?,?,?,?,?,?,?,?,?)";
	public static final String DELETE_LAB_DETAILS = "update  laboratory_details set status=?,reason=? where lab_id=? ";
	public static final String GET_SINGLE_LAB_DETAILS = "select * from laboratory_details  where lab_id=? ";
	public static final String UPDATE_LAB = "update laboratory_details set Subject=? ,Lab_Name=?,Class_Name=?, Description=? ,School_Name=?,Specialization=?,Lab_Code=? where lab_id=?";
	public static final String GET_LAB_SYLLABUS_PATH = "select Syllabus from laboratory_details where lab_id=?";
 
}
