package com.centris.campus.util;

public class SuddenHolidaySqlUtil {
	
	public static final String GET_SUDDEN_HOLIDAY_DETAILS = "SELECT DISTINCT sh.`smsDate`,cl.`Location_Name`,sh.`smsContent`,ccl.`classdetails_name_var`,ccs.`classsection_name_var`,sh.`smsCode`,sa.`sms_status`,sh.created_time FROM `sms_suddenholidays_details` sh JOIN `sms_suddenholidays_section` shs ON shs.`smsCode` = sh.`smsCode` JOIN `campus_classdetail` ccl ON ccl.`classdetail_id_int` = shs.`class_code` AND ccl.`locationId`= sh.`locationId` AND ccl.`isActive`='Y' JOIN `campus_classsection` ccs ON ccs.`classsection_id_int` = shs.`section_code` AND  ccs.`locationId`= sh.`locationId` AND ccs.`isActive`='Y' JOIN `campus_location` cl ON cl.`Location_Id` = sh.`locationId` AND cl.`isActive`='Y'JOIN `sms_audit` sa ON sa.`ServiceCode`= sh.`smsCode` where sh.`locationId`=? ORDER BY sh.`smsDate` DESC";
	public static final String STORE_SUDDENHOLIDAYS_SMS_DETAILS = "INSERT INTO `sms_suddenholidays_details`(`smsCode`,`smsDate`,`smsContent`,`created_time`,`created_by`,`locationId`) VALUES(?,?,?,?,?,?)";
	public static final String STORE_SUDDENHOLIDAYS_SECTION_DETAILS ="INSERT INTO `sms_suddenholidays_section`(`smsCode`,`section_code`,`created_time`,`created_by`,`class_code`,`acc_yearId`) VALUES(?,?,?,?,?,?)";
	public static final String VALIDATE_SUDDENHOLIDAYS_SMS = "SELECT COUNT(*) FROM `sms_suddenholidays_details` WHERE `smsDate`=? AND `smsContent`=?";
	public static final String GET_ABSENT_STUDENT_DETAILS ="SELECT DISTINCT cl.Location_Name,se.classsection_name_var,ccd.classdetails_name_var,CONCAT(st.student_fname_var,' ',st.student_lname_var)AS NAME,de.ABSENT_CODE,de.ABSENT_DATE,de.ABSENT_CONTENT,sa.sms_status,de.CREATE_TIME FROM sms_absent_details de JOIN campus_location cl ON de.LocId=cl.Location_Id AND cl.`isActive`='Y' JOIN sms_absent_section sas ON sas.ABSENT_CODE=de.ABSENT_CODE JOIN campus_classdetail ccd ON ccd.classdetail_id_int = sas.CLASS_ID AND ccd.`locationId`=de.`LocId` AND ccd.`isActive`='Y' JOIN campus_classsection se ON se.classsection_id_int = sas.SECTION_CODE AND se.`locationId`=de.`LocId` AND se.`isActive`='Y' JOIN campus_acadamicyear cay ON cay.acadamic_id = de.AccyearId AND cay.`isActive`='Y' JOIN campus_student_classdetails csc ON (csc.classdetail_id_int=sas.CLASS_ID AND csc.classsection_id_int=sas.SECTION_CODE) JOIN sms_absent_student sast ON sast.ABSENT_CODE=de.ABSENT_CODE JOIN campus_student st ON st.student_id_int = sast.STUDENT_ADM_NO JOIN sms_audit sa ON sa.ServiceCode=de.ABSENT_CODE WHERE de.LocId=?";
	public static final String STORE_ABSENT_SMS_DETAILS = "INSERT INTO sms_absent_details(ABSENT_CODE,ABSENT_DATE,ABSENT_CONTENT,LocId,CREATED_BY,AccyearId,IsStudent) VALUES(?,?,?,?,?,?,?)";
	public static final String STORE_ABSENT_STUDENT_DETAILS = "INSERT INTO sms_absent_student(ABSENT_CODE,STUDENT_ADM_NO,CREATED_BY,LOCATION_ID) VALUES(?,?,?,?)";
	public static final String STORE_ABSENT_SECTION_DETAILS = "insert into sms_absent_section(ABSENT_CODE,SECTION_CODE,CREATED_BY,CLASS_ID) values(?,?,?,?)";
	public static final String GET_COUNT_ABSENT = "select count(*) from sms_absent_details where ABSENT_CONTENT=? and ABSENT_DATE=?";
	public static final String GET_OTHER_SMS_DETAILS ="select DISTINCT sms.Date,sms.Description,concat(cls.classdetails_name_var,'-',sec.classsection_name_var) as classname,concat(st.student_fname_var,' ',student_lname_var) name from sms_any_other_sms sms join campus_classdetail cls on cls.classdetail_id_int = sms.Class_Code join campus_classsection sec on sec.classsection_id_int = sms.Section_Code join campus_student st on st.student_id_int = sms.Student_Code order by sms.Date, sms.Class_Code,sms.Section_Code,sms.Student_Code asc";
	public static final String GET_OTHER_SMS_DETAILS_FILTER ="SELECT DISTINCT sms.Date,sms.Description,CONCAT(cls.classdetails_name_var,'-',sec.classsection_name_var) AS classname,CONCAT(st.student_fname_var,' ',student_lname_var) NAME FROM sms_any_other_sms sms JOIN campus_classdetail cls ON cls.classdetail_id_int = sms.Class_Code JOIN campus_classsection sec ON sec.classsection_id_int = sms.Section_Code JOIN campus_student st ON st.student_id_int = sms.Student_Code WHERE sms.`locId` LIKE ? AND sms.`Class_Code` LIKE ? AND sms.`Section_Code` LIKE ? AND sms.`academicYear`=? and sms.Date BETWEEN ? AND ? ORDER BY sms.Date, sms.Class_Code,sms.Section_Code,sms.Student_Code ASC";
	public static final String GET_SUDDEN_HOLIDAY_DETAILS_FILTER ="SELECT sh.`SUDDENHOLIDAYS_DATE`,cl.`Location_Name`,sh.`SUDDENHOLIDAYS_CONTENT`,ccl.`classdetails_name_var`,ccs.`classsection_name_var`,sh.`SUDDENHOLIDAYS_CODE` FROM `sms_suddenholidays_details` sh JOIN `sms_suddenholidays_section`shs ON shs.`SUDDENHOLIDAYS_CODE`=sh.`SUDDENHOLIDAYS_CODE` JOIN `campus_classdetail` ccl ON ccl.`classdetail_id_int` = shs.`CLASS_CODE` AND ccl.`locationId`=sh.`LocId` JOIN `campus_classsection` ccs ON ccs.`classsection_id_int` = shs.`SECTION_CODE` AND  ccs.`locationId`=sh.`LocId` JOIN `campus_location` cl ON cl.`Location_Id` =sh.`LocId` WHERE sh.`LocId` LIKE ? AND shs.`CLASS_CODE` LIKE ? AND shs.`SECTION_CODE` LIKE ? AND shs.`ACC_YEAR`=? AND sh.`SUDDENHOLIDAYS_DATE` BETWEEN ? AND ?";
	public static final String GET_ABSENT_STUDENT_DETAILS_FILTER = "SELECT DISTINCT cl.Location_Name,se.classsection_name_var,ccd.classdetails_name_var,CONCAT(st.student_fname_var,' ',st.student_lname_var)AS NAME,de.ABSENT_CODE,de.ABSENT_DATE,de.ABSENT_CONTENT,sa.sms_status FROM sms_absent_details de JOIN campus_location cl ON de.LocId=cl.Location_Id JOIN sms_absent_section sas ON sas.ABSENT_CODE=de.ABSENT_CODE JOIN campus_classdetail ccd ON ccd.classdetail_id_int = sas.CLASS_ID JOIN campus_classsection se ON se.classsection_id_int = sas.SECTION_CODE JOIN campus_acadamicyear cay ON cay.acadamic_id = de.AccyearId JOIN campus_student_classdetails csc ON (csc.classdetail_id_int=sas.CLASS_ID AND csc.classsection_id_int=sas.SECTION_CODE) JOIN sms_absent_student sast ON sast.ABSENT_CODE=de.ABSENT_CODE JOIN campus_student st ON st.student_id_int = sast.STUDENT_ADM_NO JOIN sms_audit sa ON sa.ServiceCode=de.ABSENT_CODE WHERE de.`LocId` LIKE ? AND sas.`CLASS_ID` like ? AND sas.`SECTION_CODE` like ? AND de.`AccyearId`=? AND de.`ABSENT_DATE` BETWEEN ? AND ?";
	public static final String HOLIDAY_SMS_LIST = "SELECT count(CASE WHEN re.relationship='father' THEN par.mobileno WHEN re.relationship='mother' THEN par.student_mothermobileno_var WHEN re.relationship='guardian' THEN par.student_gardian_mobileno ELSE '1' END)AS student_contact_mobileno FROM `sms_suddenholidays_details` sd JOIN `sms_suddenholidays_section` ss ON ss.`smsCode` = sd.`smsCode` JOIN `campus_student_classdetails` cls ON cls.`classdetail_id_int` = ss.`class_code` AND cls.`classsection_id_int` = ss.`section_code` AND cls.`fms_acadamicyear_id_int` = ss.`acc_yearId` JOIN `campus_student` stu ON stu.`student_id_int` = cls.student_id_int AND stu.`student_status_var` = 'active' JOIN `campus_parentchildrelation` re ON re.`stu_addmissionNo` = cls.`student_id_int` JOIN `campus_parents` par ON par.`ParentID` = re.`parentid` WHERE sd.`smsDate` = ? AND sd.`smsCode` = ? and sd.`locationId`=?";
	public static final String STUDENT_COUNT = "SELECT COUNT(*)AS total FROM `campus_student` stu JOIN `campus_student_classdetails` cscd ON cscd.`student_id_int` = stu.`student_id_int` WHERE stu.`student_status_var`='active' AND cscd.`fms_acadamicyear_id_int`=? AND cscd.`classdetail_id_int`=? AND cscd.`classsection_id_int`=? AND cscd.`locationId`=?";
	
}
