package com.centris.campus.util;

public class TransportUtilConstants {

	public static final String GET_ALL_VEHICLE_DETAILS ="SELECT tv.VehicleCode,tv.VehicleName,tv.Vehicle_Reg_No,tv.VehicleType,tin.`Permit_validity`,CASE WHEN td.`Name` IS NULL THEN '-' WHEN td.`isActive`='N' THEN '-' WHEN td.`Name`='' THEN '-'ELSE td.`Name`END DriverName,CASE WHEN tr.`RouteName` IS NULL THEN '-' WHEN tr.isActive='N' THEN '-' WHEN tr.`RouteName`=''THEN '-'ELSE tr.`RouteName`END RouteName,CASE WHEN tv.Remark IS NULL THEN '' WHEN tv.Remark=''THEN '' ELSE tv.Remark END Remark FROM transport_vehicle tv LEFT JOIN `transport_driver_vehicle_mapping` tdvm ON tdvm.`VehicleCode`=tv.`VehicleCode`JOIN `transport_vehicle_insurancedetails` tin ON tin.`VehicleCode`=tv.`VehicleCode` LEFT JOIN `transport_driver` td ON td.`DriverCode`=tdvm.`DriverCode` AND td.`isActive` = 'Y' LEFT JOIN  `transport_vehicle_route_mapping` tvrm ON tvrm.`VehicleCode`= tv.`VehicleCode` LEFT JOIN `transport_route` tr ON tr.`RouteCode`= tvrm.`RouteCode` AND tr.`isActive` = 'Y' WHERE tv.isActive=? AND tv.locId LIKE ? ORDER BY Vehicle_Reg_No";
	public static final String SAVE_VEHICLE_DETAILS = "insert into transport_vehicle(VehicleCode, Vehicle_Reg_No,VehicleName,Engine_number,Chassis_No,VehicleType,Tax_Paid,TaxExpiryDate,Pollution,RCFileUpload,CreateDate,CreateUser,locId) values(?,?,?,?,?,?,?,?,?,?,now(),?,?)";
	public static final String CHECKING_VEHICLE_INSURANCE_DATE = "select count(*) from transport_vehicle_insurancedetails where VehicleCode= ? and (? between IssuedDate and ExpiryDate or ? between IssuedDate and ExpiryDate)";
	public static final String SAVE_VEHICLE_INSURANCE_DETAILS = "insert into transport_vehicle_insurancedetails(VehicleCode,CompanyName,IssuedDate,ExpiryDate,doneby,Fc,Permit_validity,InsuranceFleUpload,updatedBy,updatedTime) values(?,?,?,?,?,?,?,?,?,now())";
	public static final String GET_VEHCILE_INSURANCE_DETAILS = "SELECT veh.VehicleCode,veh.Vehicle_Reg_No,veh.VehicleName,veh.Engine_number,veh.Chassis_No,veh.VehicleType,veh.Tax_paid,veh.TaxExpiryDate,veh.Pollution,veh.RCFileUpload,ins.CompanyName,ins.IssuedDate,ins.ExpiryDate,ins.doneby,ins.Fc,ins.Permit_validity,ins.InsuranceFleUpload,cl.`Location_Name`,cl.`Location_Id` FROM transport_vehicle veh,transport_vehicle_insurancedetails ins ,`campus_location` cl WHERE ins.VehicleCode=veh.VehicleCode AND cl.`Location_Id`= veh.`locId` AND veh.VehicleCode=?";
	public static final String UPDATE_VEHICLE_DETAILS = "update transport_vehicle set Vehicle_Reg_No=?,VehicleName=?,Engine_number=?,Chassis_No=?,VehicleType=?,Tax_Paid=?, TaxExpiryDate=?,Pollution=?, RCFileUpload=?, UpdateDate=?,UpdateUser=?,locId=? where VehicleCode=?";
	public static final String UPDATE_VEHICLE_INSURANCE_DETAILS = "update transport_vehicle_insurancedetails set CompanyName=?,IssuedDate=?,ExpiryDate=?,doneby=?,Fc=?,Permit_validity=?,InsuranceFleUpload=?,updatedBy=?,updatedTime=? where VehicleCode=?";
	public static final String DELETE_VEHICLE_DETAILS = "update  transport_vehicle set `isActive`=?,`Remark`=? where VehicleCode=?";
	public static final String VALIDATE_VEHICLE_REG_NO = "select count(*) Vehicle_Reg_No,CASE WHEN isActive IS NULL THEN '' ELSE isActive END isActive from transport_vehicle where Vehicle_Reg_No= ? AND VehicleCode!=?"; /* AND locId=?*/
	public static final String VALIDATE_UPDATE_VEHICLE_REG_NO = "select count(*),Vehicle_Reg_No,isActive from transport_vehicle where Vehicle_Reg_No = ? and VehicleCode !=? "; /*AND locId=?*/
	public static final String VALIDATE_VEHICLE_CHASSIS_NO = "select count(*) from transport_vehicle where Chassis_No= ? AND locId=?";
	public static final String VALIDATE_UPDATE_VEHICLE_CHASSIS_NO = "select count(*) from transport_vehicle where Chassis_No = ? and VehicleCode !=? AND locId=?";
	public static final String DELETE_INSURANCE_DETAILS = "update  transport_vehicle_insurancedetails set `isActive`=?,`Remark`=? where VehicleCode=?";
	public static final String DELETE_DRIVER_VEHICLE_MAPPING = "update  transport_driver_vehicle_mapping set `isActive`=?,`Remark`=? where VehicleCode=?";
	public static final String DELETE_VEHICLE_ROUTE_MAPPIG = "update  transport_vehicle_route_mapping set `isActive`=?,`Remark`=? where VehicleCode=?";
	
	public static final String SEARCH_VEHICLE_DETAILS = "SELECT tv.VehicleCode,tv.VehicleName,tv.Vehicle_Reg_No,tv.VehicleType,tin.`Permit_validity`,CASE WHEN td.`Name` IS NULL THEN '-' WHEN td.`isActive`='N' THEN '-' WHEN td.`Name`='' THEN '-'ELSE td.`Name`END DriverName,CASE WHEN tr.`RouteName` IS NULL THEN '-' WHEN tr.`isActive` = 'N' THEN '-' WHEN tr.`RouteName`=''THEN '-'ELSE tr.`RouteName`END RouteName,CASE WHEN tv.Remark IS NULL THEN '' WHEN tv.Remark=''THEN '' ELSE tv.Remark END Remark FROM transport_vehicle tv LEFT JOIN `transport_driver_vehicle_mapping` tdvm ON tdvm.`VehicleCode`=tv.`VehicleCode` left JOIN `transport_driver` td ON td.`DriverCode`=tdvm.`DriverCode` and td.`isActive`='Y' LEFT JOIN  `transport_vehicle_route_mapping` tvrm ON tvrm.`VehicleCode`= tv.`VehicleCode` left JOIN `transport_route` tr ON tr.`RouteCode`= tvrm.`RouteCode`  AND tr.`isActive` = 'Y' JOIN `transport_vehicle_insurancedetails` tin ON tin.`VehicleCode`=tv.`VehicleCode` WHERE (tv.Vehicle_Reg_No LIKE ? OR tv.VehicleName LIKE ? OR tv.VehicleType LIKE ? OR td.`Name` LIKE ? OR tr.`RouteName` like ? OR tv.Remark LIKE ?) AND tv.locId LIKE ? AND tv.isActive= ?  ORDER BY Vehicle_Reg_No";
	public static final String CHECK_FOR_DUPLICATE_ADD_TIME ="select count(*) from transport_vehicle where Vehicle_Reg_No=? and VehicleName=? and Engine_number=? and Chassis_No=? and VehicleType=? and Tax_paid=? and Pollution=? AND locId=?";
	public static final String CHECK_FOR_DUPLICATE_UPDATE_TIME = "select count(*) from transport_vehicle where Vehicle_Reg_No=? and VehicleName=? and Engine_number=? and Chassis_No=? and VehicleType=?  and Tax_Paid=? and Pollution=? and VehicleCode!=? AND locId=?";
	public static final String VEHICLE_NAME="select VehicleCode,Vehicle_Reg_No,VehicleName,VehicleType,Fuel_Type from transport_vehicle order by VehicleName";
	public static final String DRIVER_NAME = "select DriverCode,Name from transport_driver order by Name ;";
	// route master start
	public static final String ROUTE_ALLLISTDATAS = "SELECT Route_No,RouteCode,RouteName,Start_Time,End_Time,Total_Stops,TotalDistance,HaltTime from transport_route where location_id=? and isActive='Y' order by Route_No";
	public static final String ROUTE_INSERT = "insert into transport_route(RouteCode,RouteName,Route_No,Route_logical_name,HaltTime,Start_Time,End_Time,Total_Stops,TotalDistance,CreateDate,CreateUser,location_id) values(?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String TRANSPORT_ROUTECHECK = "SELECT distinct(count(*)) FROM transport_route where Route_No=? AND location_id=?";
	public static final String TRANSPORT_ROUTECHECK_WHILE_UPDATING = "SELECT distinct(count(*)) FROM transport_route where Route_No=? and RouteCode != ? AND location_id=?";
	public static final String ROUTE_CREATEDTIME = "select CreateDate  from transport_route where RouteCode  =?";
	public static final String ROUTE_UPDATEROUTEMASTER = "update transport_route set RouteName=?,Route_No=?,Route_logical_name=?,HaltTime=?,Start_Time=?,End_Time=?,Total_Stops=?,TotalDistance=?,UpdateDate=?,UpdateUser=? where RouteCode=?";
	public static final String ROUTE_REMOVEFEE = "delete from transport_route where RouteCode=?";
	public static final String ADD_ROUTE_STOPDETAILS = "insert into transport_stopsdetails(StopCode,RouteCode,Stop_Name,ArrivalTime,HaltTime,DepTime,Distance) values(?,?,?,?,?,?,?)";
	public static final String ETID_ROUTE_ALLLISTDATAS = "select RouteName,RouteCode,Route_No,Route_logical_name,HaltTime,Start_Time,End_Time,Total_Stops,TotalDistance from transport_route where RouteCode =? AND location_id=?";
	public static final String ROUTE_SEARCHLISTDATAS = "select Route_No,RouteCode,RouteName,Route_logical_name,RouteType,Cost_per_person,Start_Time,End_Time,Total_Stops,TotalDistance, HaltTime from transport_route where Route_No like ? or RouteName like ? or Route_logical_name like ? or RouteType like ? order by Route_No";
	
	public static final String GET_STOP_NAMES = "select stage_id,stage_name from campus_fee_stage";

	// route master end

	// fuel maintenance

	public static final String GET_FUEL_DETAILS = "select f.VehicleCode,f.DriverCode,f.FuelCode,SUBSTR(f.fueldate,1,10) as fueldate,v.VehicleName,v.Vehicle_Reg_No,d.Name,f.FuelType,f.Quantity,f.FuelCost,f.MeterReading,f.Location from transport_vehicle v,transport_fuel_maintainence f,transport_driver d where f.DriverCode=d.DriverCode and f.VehicleCode=v.VehicleCode";
	public static final String ADD_FUEL_DETAILS = "insert into transport_fuel_maintainence(FuelCode,VehicleCode,fueldate,FuelType,DriverCode,Quantity,FuelCost,MeterReading,Location,CreateDate,CreateUser) values(?,?,?,?,?,?,?,?,?,?,?)";
	public static final String SEARCH_VEHICLE = "select VehicleCode,Vehicle_Reg_No,VehicleType from transport_vehicle where VehicleType like ?";
	public static final String GET_VEHICLE_NO = "select VehicleCode,Vehicle_Reg_No,Fuel_Type from transport_vehicle where VehicleCode=?";
	public static final String DELETE_FUEL_DETAILS = "Delete from transport_fuel_maintainence where FuelCode=?";
	public static final String EDIT_FUEL_DETAILS = "select ve.VehicleCode,dr.DriverCode,fu.FuelCode,ve.VehicleName,fu.fueldate,ve.Vehicle_Reg_No,dr.Name,fu.FuelType,fu.Quantity,fu.FuelCost,fu.MeterReading,fu.Location from transport_fuel_maintainence fu join transport_driver dr on dr.DriverCode=fu.DriverCode join transport_vehicle ve on ve.VehicleCode=fu.VehicleCode where fu.FuelCode= ?";
	public static final String UPDATE_FUEL_DETAILS = "update transport_fuel_maintainence set VehicleCode=?,fueldate=?,FuelType=?,DriverCode=?,Quantity=?,FuelCost=?,MeterReading=?,Location=?,UpdateDate=?,UpdateUser=? where FuelCode=?";
	public static final String SEARCH_FUEL_DETAILS = "select fu.fueldate,fu.Location,fu.FuelType,ve.VehicleType,ve.Vehicle_Reg_No,dr.Name,fu.Quantity,fu.FuelCost,fu.MeterReading from transport_fuel_maintainence fu join transport_vehicle ve on ve.VehicleCode=fu.VehicleCode join transport_driver dr on dr.DriverCode=fu.DriverCode where (fu.fueldate like ? or fu.Location like ? or fu.FuelType like ? or ve.VehicleType like ? or ve.Vehicle_Reg_No like ? or dr.Name LIKE ? )";
	public static final String SEARCH_DRIVER = "select DriverCode,Name from transport_driver where Name like ?";

	// Driver master

	public static final String GET_DRIVER_LIST = "select * from transport_driver order by Name";
	public static final String ADD_DRIVER = "insert into transport_driver (DriverCode,type,Name,FatherName,DOB,MobileNo,EmergencyContactNo,Address,DOJ,Age,Gender,DLNo,DLExpirayDate,LicencetoDrive,CreateDate,CreateUser,Experience,DrivingLicenceFile,locId) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,now(),?,?,?,?)";
	public static final String GET_DRIVER_DETAILS = "select locId,DriverCode,Name,FatherName,DOB,MobileNo,EmergencyContactNo,Experience,Address,DOJ,Age,Gender,DLNo,DLExpirayDate,LicencetoDrive,DrivingLicenceFile from transport_driver where DriverCode=?";
	public static final String DELETE_DRIVER = "delete from transport_driver where DriverCode=?";
	public static final String SEARCH_DRIVER_DETAILS = "select * from transport_driver where  Name like ? or DOJ like ? or MobileNo like ? or DLNo like ? or DLIssuedDate like ? or DLExpirayDate like ?";
	public static final String UPDATE_DRIVER = "update transport_driver set Name=?,FatherName=?,DOB=?,MobileNo=?,EmergencyContactNo=?,Address=?,DOJ=?,Age=?,Gender=?,DLNo=?,DLExpirayDate=?,LicencetoDrive=?,UpdateDate=?,Experience=?,DrivingLicenceFile=?,locId=?,UpdateUser=? where DriverCode=?"; /*UpdateDate=? ,*/
	public static final String VALIDATE_DRIVER = "select count(*) driverCount from transport_driver where  Name=? and DOB=? and MobileNo=? and Address=? and DOJ=?";

	// driver mapping
	public static final String GET_UNMAPPED_DRIVER_DETAILS1 ="SELECT DriverCode,NAME,MobileNo,Experience,DOJ,DLNo,DLExpirayDate,LicencetoDrive FROM transport_driver WHERE locId=? AND `isActive` = 'Y' ORDER BY NAME ";
	public static final String GET_UNMAPPED_DRIVER_DETAILS = "select distinct td.DriverCode,td.Name from transport_driver td,transport_driver_vehicle_mapping tdm where td.DriverCode not in (select DriverCode from transport_driver_vehicle_mapping)";
	public static final String GET_DRIVER_DETAILS_BY_ID ="SELECT DriverCode,NAME,MobileNo,Experience,DOJ,DLNo,DLExpirayDate,LicencetoDrive FROM transport_driver WHERE  `isActive` = 'Y' and DriverCode=? ";
	public static final String GET_UNMAPPED_DRIVER_DETAILS_WHILE_UPDATE = "select distinct td.DriverCode,td.Name from transport_driver td,transport_driver_vehicle_mapping tdm where td.DriverCode not in (select DriverCode from transport_driver_vehicle_mapping where VehicleCode != ?)";
	public static final String GET_SINGLE_DRIVER_DETAILS = "select distinct dr.locId,dr.DriverCode,dr.Name,dr.MobileNo,dr.Experience,dr.DOJ,dr.DLNo,dr.DLIssuedDate,dr.DLExpirayDate,dr.LicencetoDrive from transport_vehicle veh,transport_vehicle_insurancedetails ins,transport_driver dr,transport_driver_vehicle_mapping drm where ins.VehicleCode=veh.VehicleCode and dr.DriverCode in(select DriverCode from transport_driver_vehicle_mapping where VehicleCode =?) and veh.VehicleCode=?";
	public static final String MAP_DRIVER_VEHICLE_INSERTING = "insert into transport_driver_vehicle_mapping(DriverCode,VehicleCode,Createdby,Createtime)value(?,?,?,now())";
	public static final String MAP_DRIVER_VEHICLE_WHILE_UPDATE = "update transport_driver_vehicle_mapping set DriverCode=?,VehicleCode=?,Modifiedby=?,ModifiedDate=now() where VehicleCode=?";
	public static final String CHECKING_DRIVER = "select count(*) from transport_driver_vehicle_mapping where DriverCode=?";
	public static final String VALIDATE_LICENSE = "select count(*) driverCount from transport_driver where  DLNo=? AND locId=?";
	// route
	public static final String GET_ROUTE_NAMES = "select RouteCode,RouteName from transport_route order by RouteName";
	public static final String GET_ROUTE_DETAILS = "select RouteCode,RouteName,TotalDistance,Route_No,Total_Stops,Destination,HaltTime from transport_route where RouteCode = ? and `isActive`='Y' order by RouteName";
	public static final String MAP_DRIVER_VEHICLE_ROUTE_MAPPING = "insert into transport_vehicle_route_mapping(RouteCode,VehicleCode,CreateUser,CreateDate)value(?,?,?,now())";
	public static final String MAP_DRIVER_VEHICLE_ROUTE_MAPPING_UPDATING = "update transport_vehicle_route_mapping set RouteCode=?,VehicleCode=?,CreateUser=?,CreateDate=now() where  VehicleCode =?";
	public static final String CHECK_VEHICLE_MAPPING = "select count(*) from transport_vehicle_route_mapping where VehicleCode = ?";
	public static final String GET_ROUTE_DETAILS_EDIT = "select rt.RouteCode,rt.RouteName,rt.TotalDistance,rt.Route_No,rt.Total_Stops,rt.HaltTime from transport_route rt,transport_vehicle_route_mapping tmv where rt.RouteCode = tmv.RouteCode and tmv.VehicleCode in(select VehicleCode from transport_vehicle where VehicleCode = ?)";

	public static final String ROUTE_ALLLISTDATASTOP = "select tr.RouteName,tr.RouteCode,tr.Route_No,tr.Start_Time,tr.End_Time,tr.Total_Stops,tr.TotalDistance,tr.HaltTime,tr.Destination,sto.Stop_Name,sto.ArrivalTime,sto.DepTime,sto.Distance from transport_route tr join transport_stopsdetails sto on sto.RouteCode=tr.RouteCode";
	public static final String ROUTE_INSERT_STAGE = "insert into transport_route_stage_mapping(RouteCode,StageCode,CreatedBy,loc_id) values(?,?,?,?)";
	public static final String ROUTE_MAPPED_STAGE = "update campus_fee_stage set status='mapped' where stage_id=?" ;
	public static final String ETID_ROUTE_STAGES = "select DISTINCT cfs.stage_name,trsm.StageCode from transport_route_stage_mapping trsm join campus_fee_stage cfs on trsm.StageCode=cfs.stage_id AND cfs.location=trsm.loc_id where trsm.RouteCode=? AND cfs.location=? and cfs.isActive='Y' order by stage_name" ;
	public static final String UNMMAPEDSTAGES = "SELECT DISTINCT css.stage_name,css.stage_id FROM campus_fee_stage css LEFT JOIN transport_route_stage_mapping trsm ON css.stage_id=trsm.StageCode AND css.location=trsm.loc_id AND trsm.RouteCode=? AND css.location=? WHERE css.isActive='Y' order by stage_name "; /*and trsm.StageCode IS NULL OR trsm.RouteCode=?*/
	public static final String DELETE_INSERT_STAGE = "delete from transport_route_stage_mapping where RouteCode=?";

	public static final String GET_ROUTE_NAMES_BY_LOCATION = "select tr.RouteCode,tr.RouteName from transport_route tr,transport_route_stage_mapping tsm where tr.RouteCode=tsm.RouteCode and tsm.StageCode=? and tr.isActive='Y'";
	
	public static final String GET_ROUTE_DETAILS_BY_VECHILE = "select * from transport_route  where location_id=? AND `isActive`='Y' order by RouteName";
	public static final String INSERT_VECHICLE_TYPE = "insert into transport_typedetails(type_id,type_name,type_description,createdby) VALUES(?,?,?,?)";
	public static final String GET_ALL_VEHICLE_TYPE_DETAILS = "select type_id,type_name,type_description from transport_typedetails order by type_name";


	public static final String EDIT_TRANSPORT_CATEGORY_DETAILS = "select type_id,type_name,type_description from transport_typedetails  where type_id=?";
	public static final String DELETE_VEHICLE_TYPE_DETAILS = "delete from transport_typedetails where type_id=?";
	public static final String VALIDATE_VEHICLE_TYPE = "select count(*),isActive from transport_typedetails where type_name= ? AND type_id <> ?";
	public static final String UPDATE_VECHICLE_TYPE = "update transport_typedetails set type_name=?,type_description=?,updatedby=?,updaeddate=? where type_id=?";
	public static final String SEARCH_VEHICLE_TYPE = "select type_id,type_name,type_description from transport_typedetails where (type_id like ? or type_name like ? or type_description like ?) order by type_name";
	public static final String STUDENT_DETAILS_TRANSPORT = "select cs.student_admissionno_var,concat(cs.student_fname_var,' ',cs.student_lname_var) as student,cp.parentid,cc.classdetail_id_int,cc.classdetails_name_var  from campus_student cs join campus_parentchildrelation cp  on cs.student_id_int= cp.stu_addmissionNo and cs.student_id_int=? and cp.stu_addmissionNo=? and cs.fms_acadamicyear_id_int=? and cs.locationId=? join campus_classdetail cc  where cc.classdetail_id_int=? and cc.locationId=? ";
	public static final String GET_STUDENTS_BY_LOCATION_ACCYEAR = "select distinct st.student_id_int,cstd.classsection_id_int,cstd.fms_acadamicyear_id_int,cstd.classdetail_id_int,cstd.locationId,case when cstd.student_rollno is null then '-' else cstd.student_rollno end student_rollno,st.student_admissionno_var,cstd.classdetail_id_int,cstd.classsection_id_int,case when st.student_lname_var is null then st.student_fname_var else concat(st.student_fname_var,' ',st.student_lname_var)end studentName,cls.classdetails_name_var,sec.classsection_name_var,st.student_dob_var,st.student_status_var from campus_student st join campus_student_classdetails cstd on st.student_id_int=cstd.student_id_int join campus_classdetail cls on cls.classdetail_id_int=cstd.classdetail_id_int join campus_classsection sec on sec.classsection_id_int=cstd.classsection_id_int join campus_acadamicyear acc on acc.acadamic_id=cstd.fms_acadamicyear_id_int left join campus_student_transportdetails tra on tra.student_id_int = cstd.student_id_int join campus_location cl on cl.Location_Id=cstd.locationId where cstd.locationId like ? and cstd.fms_acadamicyear_id_int like ? and st.student_status_var='active' and cls.isActive='Y' and sec.isActive='Y' and acc.isActive='Y' and cl.isActive='Y' order by length(cls.classdetail_id_int),cls.classdetail_id_int,sec.classsection_name_var,studentName";
	public static final String GET_STUDENT_LIST = "select distinct csc.locationId,csc.classsection_id_int,csc.classdetail_id_int,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var, case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var) end studentname,case when csc.student_rollno is null then '-' else csc.student_rollno end student_rollno,ccd.classdetails_name_var,ccs.classsection_name_var from campus_student stu join campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int  where csc.locationId like ? and csc.fms_acadamicyear_id_int=? and tra.isTransport = 'Y' order by CAST(SUBSTR(csc.fms_acadamicyear_id_int,4) AS UNSIGNED),CAST(SUBSTR(csc.locationId,4) AS UNSIGNED),length(csc.classdetail_id_int),csc.classdetail_id_int,ccs.classsection_name_var,studentname";
	public static final String GET_FILTERED_STUDENTDETAILS = "select distinct csc.locationId,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var,csc.classdetail_id_int,ccs.classsection_id_int,stu.student_status_var,acy.acadamic_year, case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var)end studentname,case when csc.student_rollno is null then '-' else csc.student_rollno end student_rollno,ccd.classdetails_name_var,ccs.classsection_name_var,stu.student_dob_var from campus_student stu JOIN campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int join campus_acadamicyear acy on csc.fms_acadamicyear_id_int=acy.acadamic_id left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int where tra.isTransport = 'Y' and  csc.locationId like ? and csc.fms_acadamicyear_id_int=? and csc.classdetail_id_int like ?  order by length(csc.classdetail_id_int),csc.classdetail_id_int,ccs.classsection_name_var,studentName";
	public static final String GET_FILTERED_STUDENTD_BY_SECTION = "select distinct ccd.classdetail_id_int,csc.classsection_id_int,csc.secondlanguage,csc.thirdlanguage,csc.specilization,stu.student_admissionno_var,stu.student_gender_var,csc.locationId,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var,acy.acadamic_year , case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var)end studentname,CASE WHEN csc.student_rollno IS NULL THEN '-' ELSE csc.student_rollno END student_rollno,ccd.classdetails_name_var,ccs.classsection_name_var from campus_student stu JOIN campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int join campus_acadamicyear acy on csc.fms_acadamicyear_id_int=acy.acadamic_id left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int where csc.locationId like ? and csc.fms_acadamicyear_id_int=? and tra.isTransport = 'Y' and csc.classdetail_id_int=? and csc.classsection_id_int like ? order by CAST(csc.student_rollno AS UNSIGNED)";
	public static final String GET_STUDENTS_SEARCH_BY_LIST = "select distinct csc.classdetail_id_int,csc.classsection_id_int,csc.locationId,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var,case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var) end studentName,case when csc.student_rollno is null then '-' else csc.student_rollno end student_rollno,ccd.classdetails_name_var,ccs.classsection_name_var from campus_student stu join campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int where tra.isTransport = 'Y' and (stu.student_admissionno_var like ? or stu.student_fname_var like ? or stu.student_lname_var like ? or concat(stu.student_fname_var,' ',stu.student_lname_var) like ? or ccs.classsection_name_var like ? or ccd.classdetails_name_var like ? or CONCAT(ccd.classdetails_name_var,'-',ccs.classsection_name_var) like ?)";
	public static final String GET_STU_DETAILS = "select DISTINCT st.student_imgurl_var,concat(st.student_fname_var,' ',st.student_lname_var)as student,tra.isTransport,tra.StageId,tra.TransportType,tra.route,tra.start_month,tra.end_month,st.student_admissionno_var,cd.classdetails_name_var,csc.student_status,cs.classsection_name_var,pc.address from campus_student st join campus_student_classdetails csc on st.student_id_int = csc.student_id_int join campus_parentchildrelation par on par.stu_addmissionNo = st.student_id_int join campus_parents pc on pc.ParentID = par.parentid join campus_classdetail cd on cd.classdetail_id_int = csc.classdetail_id_int join campus_classsection cs on cs.classsection_id_int = csc.classsection_id_int join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int AND tra.fms_acadamicyear_id_int=csc.fms_acadamicyear_id_int where st.student_id_int = ? and csc.locationId = ? and csc.classdetail_id_int = ? and csc.classsection_id_int = ? and csc.fms_acadamicyear_id_int = ? AND tra.isTransport=?";
	public static final String GET_STUDENTS_SEARCH_BY_ACCYEAR = "select distinct csc.classdetail_id_int,csc.classsection_id_int,csc.locationId,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var,case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var) end studentName,case when csc.student_rollno is null then '-' else csc.student_rollno end student_rollno,ccd.classdetails_name_var,ccs.classsection_name_var from campus_student stu join campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int where tra.isTransport = 'Y' and (stu.student_admissionno_var like ? or stu.student_fname_var like ? or stu.student_lname_var like ? or concat(stu.student_fname_var,' ',stu.student_lname_var) like ? or ccs.classsection_name_var like ? or ccd.classdetails_name_var like ? or CONCAT(ccd.classdetails_name_var,'-',ccs.classsection_name_var) like ?) and csc.fms_acadamicyear_id_int like ?";
	public static final String GET_STUDENTS_SEARCH_BY_LOCATION = "select distinct csc.classdetail_id_int,csc.classsection_id_int,csc.locationId,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var,case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var) end studentName,case when csc.student_rollno is null then '-' else csc.student_rollno end student_rollno ,ccd.classdetails_name_var,ccs.classsection_name_var from campus_student stu join campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int where tra.isTransport = 'Y' and (stu.student_admissionno_var like ? or stu.student_fname_var like ? or stu.student_lname_var like ? or concat(stu.student_fname_var,' ',stu.student_lname_var) like ? or ccs.classsection_name_var like ? or ccd.classdetails_name_var like ? or CONCAT(ccd.classdetails_name_var,'-',ccs.classsection_name_var) like ?) and csc.locationId like ?";
	public static final String GET_STUDENTS_SEARCH_BY_FILTER = "select distinct csc.classdetail_id_int,csc.classsection_id_int,csc.locationId,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var,case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var) end studentName,case when csc.student_rollno is null then '-' else csc.student_rollno end student_rollno ,ccd.classdetails_name_var,ccs.classsection_name_var from campus_student stu join campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int where tra.isTransport = 'Y' and (stu.student_admissionno_var like ? or stu.student_fname_var like ? or stu.student_lname_var like ? or concat(stu.student_fname_var,' ',stu.student_lname_var) like ? or ccs.classsection_name_var like ? or ccd.classdetails_name_var like ? or CONCAT(ccd.classdetails_name_var,'-',ccs.classsection_name_var) like ?) and csc.locationId like ?";
	public static final String GET_STUDENTS_SEARCH_BY_CLASS = "select distinct csc.classdetail_id_int,csc.classsection_id_int,csc.locationId,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var,case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var) end studentName,case when csc.student_rollno is null then '-' else csc.student_rollno end student_rollno ,ccd.classdetails_name_var,ccs.classsection_name_var from campus_student stu join campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int where tra.isTransport = 'Y' and (stu.student_admissionno_var like ? or stu.student_fname_var like ? or stu.student_lname_var like ? or concat(stu.student_fname_var,' ',stu.student_lname_var) like ? or ccs.classsection_name_var like ? or ccd.classdetails_name_var like ? or CONCAT(ccd.classdetails_name_var,'-',ccs.classsection_name_var) like ?) and csc.locationId like ? and csc.fms_acadamicyear_id_int like ? and ccd.classdetail_id_int like ?";
	public static final String GET_STUDENTS_SEARCH_BY_ALL_FILTER = "select distinct csc.classdetail_id_int,ccs.classsection_id_int,csc.locationId,csc.fms_acadamicyear_id_int,stu.student_id_int,stu.student_admissionno_var,case when stu.student_lname_var is null then stu.student_fname_var else concat(stu.student_fname_var,' ',stu.student_lname_var) end studentName,case when csc.student_rollno is null then '-' else csc.student_rollno end student_rollno,ccd.classdetails_name_var,ccs.classsection_name_var from campus_student stu join campus_student_classdetails csc on stu.student_id_int=csc.student_id_int join campus_classdetail ccd on csc.classdetail_id_int=ccd.classdetail_id_int join campus_classsection ccs on csc.classsection_id_int=ccs.classsection_id_int left join campus_student_transportdetails tra on tra.student_id_int = csc.student_id_int where tra.isTransport = 'Y' and (stu.student_admissionno_var like ? or stu.student_fname_var like ? or stu.student_lname_var like ? or concat(stu.student_fname_var,' ',stu.student_lname_var) like ? or ccs.classsection_name_var like ? or ccd.classdetails_name_var like ? or CONCAT(ccd.classdetails_name_var,'-',ccs.classsection_name_var) like ?) and csc.locationId like ? and csc.fms_acadamicyear_id_int like ? and ccd.classdetail_id_int=? and ccs.classsection_id_int=?";
	public static final String UPDATE_TRANSPORT_REQUEST = "update campus_student_transportdetails set isTransport = 'Y',StageId = ?,route = ?,start_month = ?,end_month = ?,NumberOfMonth=?,TransportType=? where student_id_int = ? and fms_acadamicyear_id_int = ? and locationId = ?";
	public static final String UPDATE_TRANSPORT_WAIVEDOFF = "update campus_student_transportdetails set isTransport = 'N',StageId ='0',route ='NIL' where student_id_int = ? and fms_acadamicyear_id_int = ? and locationId = ?";
	public static final String GETSTUDENTBUSCARDDETAILS = "SELECT CONCAT(st.student_fname_var,' ',st.student_lname_var) AS student,pa.mobileno,CASE WHEN trf.reciept_no IS NULL THEN '-' ELSE trf.reciept_no END reciept_no,CONCAT(cd.classdetails_name_var,' ',cs.classsection_name_var)AS class,cf.stage_name,CASE WHEN rn.RouteName IS NULL THEN '-' ELSE rn.RouteName END RouteName FROM campus_student st JOIN campus_student_transportdetails tra ON st.student_id_int = tra.student_id_int JOIN campus_student_classdetails csc ON csc.student_id_int = st.student_id_int JOIN campus_classdetail cd ON  csc.classdetail_id_int = cd.classdetail_id_int AND csc.locationId = cd.locationId JOIN campus_classsection cs ON csc.classsection_id_int = cs.classsection_id_int AND csc.locationId = cs.locationId JOIN campus_parentchildrelation pra ON pra.stu_addmissionNo = tra.student_id_int JOIN campus_parents pa ON pa.parentid = pra.ParentID  JOIN transport_route rn ON rn.RouteCode = tra.route JOIN campus_fee_stage cf ON cf.stage_id = tra.StageId   LEFT  JOIN campus_tranport_fee_collection_details trf ON tra.student_id_int=trf.admissionNo AND accYear = ? AND trf.termcode = ? WHERE  isTransport = 'Y' AND csc.student_id_int = ? AND csc.fms_acadamicyear_id_int = ? AND csc.locationId =? GROUP BY trf.termcode";
	public static final String GET_STAGE_LIST = "SELECT stage_id,stage_name FROM campus_fee_stage WHERE location=? AND isActive='Y' ORDER BY stage_name";
	public static final String ROUTE_LIST_BY_STATUS_AND_SEARCH = "SELECT tr.Route_No,tr.RouteCode,tr.RouteName,tr.Start_Time,tr.End_Time,tr.Total_Stops,tr.TotalDistance,tr.HaltTime,CASE WHEN tr.remarks IS NULL THEN '' WHEN tr.remarks='' THEN '' ELSE tr.remarks end remarks FROM transport_route tr join campus_location cl on cl.Location_Id=tr.location_id WHERE tr.location_id=? AND (tr.Route_No LIKE ? OR tr.RouteName LIKE ? OR tr.Start_Time LIKE ? OR tr.End_Time LIKE ? OR tr.Total_Stops LIKE ? OR tr.TotalDistance LIKE ? OR tr.HaltTime LIKE ? OR tr.remarks LIKE ?) and tr.isActive=? and cl.isActive='Y' ORDER BY tr.Route_No";
	public static final String ROUTE_DETAILS_UPDATED_BY_STATUS = "UPDATE transport_route SET isActive=?,remarks=? WHERE RouteCode=? AND location_id=?";
	public static final String GET_ALL_VEHICLE_TYPE_DETAILS_BY_STATUS = "select type_id,type_name,type_description,CASE WHEN remarks IS NULL THEN '' WHEN remarks='' THEN '' ELSE remarks END remarks from transport_typedetails where isActive=? and (type_name LIKE ? or type_description like ? or remarks like ?) order by type_name";
	public static final String UPDATE_VEHICLE_TYPE_DETAILS_BY_STATUS = "UPDATE transport_typedetails SET isActive=?,remarks=? WHERE type_id=?";
	public static final String GET_DRIVER_LIST_BY_STATUS_AND_SEARCH = "SELECT DISTINCT DLExpirayDate,DLNo,TYPE,NAME,DOB,DOJ,MobileNo,DriverCode,FatherName,EmergencyContactNo,Address,Age,Gender,LicencetoDrive,Experience,CASE WHEN remarks IS NULL THEN '' WHEN remarks='' THEN '' ELSE remarks END remarks FROM transport_driver WHERE isActive=? AND(NAME LIKE ? OR DOJ LIKE ? OR MobileNo LIKE ? OR DLNo LIKE ? OR DLExpirayDate LIKE ? OR remarks LIKE ?) and locId like ? ORDER BY NAME";
	public static final String UPDATE_DRIVER_MASTER_STATUS = "UPDATE transport_driver SET isActive=?,remarks=? WHERE DriverCode=?";
	public static final String VALIDATE_DRIVER_CODE ="select count(*) from transport_driver_vehicle_mapping where DriverCode=?";
	public static final String GET_TOTAL_YEAR_COLLECTION ="SELECT SUM(ctfc.amount_paid) AS TOTAL  FROM campus_tranport_fee_collection_details ctfc JOIN campus_fee_transport_termdetails cftt ON cftt.termid=ctfc.termcode  WHERE ctfc.accYear =? AND cftt.locationId=? ";
	public static final String GET_TODAY_COLLECTION ="SELECT COALESCE(SUM(ctfc.amount_paid),0) AS total FROM  campus_tranport_fee_collection_details ctfc JOIN campus_fee_transport_termdetails cftt ON cftt.termid=ctfc.termcode  WHERE ctfc.paidDate =? AND cftt.locationId=? ";

}
